packages:
  - pkg/rest-js
  - pkg/test/rest-js

autoInstallPeers: true

gitChecks: false

linkWorkspacePackages: true

onlyBuiltDependencies:
  - core-js
  - esbuild
  - msw
  - protobufjs

prefer-workspace-packages: true

recursive-install: true

strictPeerDependencies: false
