-- The durable record of asynchronous work. A request becomes a row here, a worker claims it, and the
-- row survives a restart in between. The table knows nothing about narrative: kind is a string and
-- payload is opaque JSON.
--
-- Several columns depart from the scaffold items table. Each departure is load-bearing:
--
--   * Timestamps are full precision and generated by the database with clock_timestamp(). In a
--     distributed queue the database is the single clock, so application-server skew never enters
--     lease arithmetic. CURRENT_TIMESTAMP and now() are frozen at transaction start, so a column
--     written inside a transaction could never advance past the value its neighbors already hold.
--   * Identifiers are time-ordered (uuidv7, native to the PostgreSQL 18 image this service pins), so
--     a table with heavy insert churn keeps index locality.
--   * status is text with a CHECK list. Adding a value stays a plain migration.
--   * owner_id, not actor_id, so one word means one thing across the whole queue.
CREATE TABLE jobs (
  id uuid PRIMARY KEY NOT NULL DEFAULT uuidv7(),
  kind text NOT NULL CHECK (kind <> ''),
  payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  /* The acting user, taken from the verified token and never from the payload. Reads are scoped by
  it inside the statement, so a caller that omits it fails to scan rather than leaking. */
  owner_id uuid NOT NULL,
  idempotency_key text CHECK (idempotency_key <> ''),
  /* Digest of the request body, defaulting in the application to the digest of an empty body. NOT
  NULL so a same-key-different-payload check cannot pass on a null stored side. */
  request_fingerprint bytea NOT NULL,
  status text NOT NULL DEFAULT 'pending' CHECK (
    status IN (
      'pending',
      'claimed',
      'succeeded',
      'failed',
      'abandoned',
      'cancelled'
    )
  ),
  attempt smallint NOT NULL DEFAULT 0 CHECK (attempt >= 0),
  /* One attempt by default, which is the right floor for a priced call. */
  max_attempts smallint NOT NULL DEFAULT 1 CHECK (max_attempts >= 1),
  run_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  lease_expires_at timestamptz,
  claimed_by text,
  /* Ships ahead of the endpoint that writes it. The claim predicate sits behind a partial index on
  the hot path, and changing that predicate later means re-reasoning about the index on a table
  holding live rows. */
  cancel_requested_at timestamptz,
  /* The provider's own identifier for the operation this job started. It is what lets a job whose
  worker died mid-call re-attach to that operation instead of paying for a second generation. One
  column while the table is empty; a migration on a live table later. */
  provider_call_id text,
  result jsonb,
  error jsonb,
  created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  settled_at timestamptz,
  expires_at timestamptz,
  CONSTRAINT jobs_lease_matches_status CHECK (
    (status = 'claimed') = (lease_expires_at IS NOT NULL)
  ),
  CONSTRAINT jobs_terminal_fields CHECK (
    (
      status IN ('succeeded', 'failed', 'abandoned', 'cancelled')
    ) = (
      settled_at IS NOT NULL
      AND expires_at IS NOT NULL
    )
  )
);

-- kind is part of the key. Without it, one owner's keys collide across job kinds and the second
-- submission is treated as a replay of the first.
CREATE UNIQUE INDEX jobs_idempotency_idx ON jobs (owner_id, kind, idempotency_key)
WHERE
  idempotency_key IS NOT NULL;

-- Each partial index matches the predicate that will run against it, so none of them grows as
-- terminal rows accumulate and no hot path degrades over the life of the table.
CREATE INDEX jobs_dispatch_idx ON jobs (run_at)
WHERE
  status = 'pending';

CREATE INDEX jobs_lease_idx ON jobs (lease_expires_at)
WHERE
  status = 'claimed';

CREATE INDEX jobs_retention_idx ON jobs (expires_at)
WHERE
  expires_at IS NOT NULL;

CREATE INDEX jobs_owner_idx ON jobs (owner_id, created_at DESC);

-- Continuous insert-update-delete churn is what kills database-backed queues: under the defaults,
-- dead tuples accumulate faster than the table is vacuumed and the claim query slows down with no
-- other symptom.
ALTER TABLE jobs
SET
  (
    autovacuum_vacuum_scale_factor = 0.02,
    autovacuum_vacuum_threshold = 25,
    autovacuum_analyze_scale_factor = 0.02
  );
