// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package coremocks

import (
	"context"

	"github.com/a-novel/service-narrative-engine/internal/core"
	"github.com/a-novel/service-narrative-engine/internal/dao"
	mock "github.com/stretchr/testify/mock"
)

// NewMockIdeaCreateDao creates a new instance of MockIdeaCreateDao. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIdeaCreateDao(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIdeaCreateDao {
	mock := &MockIdeaCreateDao{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIdeaCreateDao is an autogenerated mock type for the IdeaCreateDao type
type MockIdeaCreateDao struct {
	mock.Mock
}

type MockIdeaCreateDao_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIdeaCreateDao) EXPECT() *MockIdeaCreateDao_Expecter {
	return &MockIdeaCreateDao_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockIdeaCreateDao
func (_mock *MockIdeaCreateDao) Exec(ctx context.Context, request *dao.IdeaInsertRequest) (*dao.Idea, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 *dao.Idea
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dao.IdeaInsertRequest) (*dao.Idea, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dao.IdeaInsertRequest) *dao.Idea); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dao.Idea)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dao.IdeaInsertRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIdeaCreateDao_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockIdeaCreateDao_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - request *dao.IdeaInsertRequest
func (_e *MockIdeaCreateDao_Expecter) Exec(ctx any, request any) *MockIdeaCreateDao_Exec_Call {
	return &MockIdeaCreateDao_Exec_Call{Call: _e.mock.On("Exec", ctx, request)}
}

func (_c *MockIdeaCreateDao_Exec_Call) Run(run func(ctx context.Context, request *dao.IdeaInsertRequest)) *MockIdeaCreateDao_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dao.IdeaInsertRequest
		if args[1] != nil {
			arg1 = args[1].(*dao.IdeaInsertRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIdeaCreateDao_Exec_Call) Return(idea *dao.Idea, err error) *MockIdeaCreateDao_Exec_Call {
	_c.Call.Return(idea, err)
	return _c
}

func (_c *MockIdeaCreateDao_Exec_Call) RunAndReturn(run func(ctx context.Context, request *dao.IdeaInsertRequest) (*dao.Idea, error)) *MockIdeaCreateDao_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIdeaHistoryDao creates a new instance of MockIdeaHistoryDao. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIdeaHistoryDao(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIdeaHistoryDao {
	mock := &MockIdeaHistoryDao{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIdeaHistoryDao is an autogenerated mock type for the IdeaHistoryDao type
type MockIdeaHistoryDao struct {
	mock.Mock
}

type MockIdeaHistoryDao_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIdeaHistoryDao) EXPECT() *MockIdeaHistoryDao_Expecter {
	return &MockIdeaHistoryDao_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockIdeaHistoryDao
func (_mock *MockIdeaHistoryDao) Exec(ctx context.Context, request *dao.IdeaVersionListRequest) ([]*dao.IdeaVersion, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 []*dao.IdeaVersion
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dao.IdeaVersionListRequest) ([]*dao.IdeaVersion, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dao.IdeaVersionListRequest) []*dao.IdeaVersion); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*dao.IdeaVersion)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dao.IdeaVersionListRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIdeaHistoryDao_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockIdeaHistoryDao_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - request *dao.IdeaVersionListRequest
func (_e *MockIdeaHistoryDao_Expecter) Exec(ctx any, request any) *MockIdeaHistoryDao_Exec_Call {
	return &MockIdeaHistoryDao_Exec_Call{Call: _e.mock.On("Exec", ctx, request)}
}

func (_c *MockIdeaHistoryDao_Exec_Call) Run(run func(ctx context.Context, request *dao.IdeaVersionListRequest)) *MockIdeaHistoryDao_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dao.IdeaVersionListRequest
		if args[1] != nil {
			arg1 = args[1].(*dao.IdeaVersionListRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIdeaHistoryDao_Exec_Call) Return(ideaVersions []*dao.IdeaVersion, err error) *MockIdeaHistoryDao_Exec_Call {
	_c.Call.Return(ideaVersions, err)
	return _c
}

func (_c *MockIdeaHistoryDao_Exec_Call) RunAndReturn(run func(ctx context.Context, request *dao.IdeaVersionListRequest) ([]*dao.IdeaVersion, error)) *MockIdeaHistoryDao_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIdeaVersionInsertDao creates a new instance of MockIdeaVersionInsertDao. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIdeaVersionInsertDao(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIdeaVersionInsertDao {
	mock := &MockIdeaVersionInsertDao{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIdeaVersionInsertDao is an autogenerated mock type for the IdeaVersionInsertDao type
type MockIdeaVersionInsertDao struct {
	mock.Mock
}

type MockIdeaVersionInsertDao_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIdeaVersionInsertDao) EXPECT() *MockIdeaVersionInsertDao_Expecter {
	return &MockIdeaVersionInsertDao_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockIdeaVersionInsertDao
func (_mock *MockIdeaVersionInsertDao) Exec(ctx context.Context, request *dao.IdeaVersionInsertRequest) (*dao.IdeaVersion, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 *dao.IdeaVersion
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dao.IdeaVersionInsertRequest) (*dao.IdeaVersion, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dao.IdeaVersionInsertRequest) *dao.IdeaVersion); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dao.IdeaVersion)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dao.IdeaVersionInsertRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIdeaVersionInsertDao_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockIdeaVersionInsertDao_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - request *dao.IdeaVersionInsertRequest
func (_e *MockIdeaVersionInsertDao_Expecter) Exec(ctx any, request any) *MockIdeaVersionInsertDao_Exec_Call {
	return &MockIdeaVersionInsertDao_Exec_Call{Call: _e.mock.On("Exec", ctx, request)}
}

func (_c *MockIdeaVersionInsertDao_Exec_Call) Run(run func(ctx context.Context, request *dao.IdeaVersionInsertRequest)) *MockIdeaVersionInsertDao_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dao.IdeaVersionInsertRequest
		if args[1] != nil {
			arg1 = args[1].(*dao.IdeaVersionInsertRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIdeaVersionInsertDao_Exec_Call) Return(ideaVersion *dao.IdeaVersion, err error) *MockIdeaVersionInsertDao_Exec_Call {
	_c.Call.Return(ideaVersion, err)
	return _c
}

func (_c *MockIdeaVersionInsertDao_Exec_Call) RunAndReturn(run func(ctx context.Context, request *dao.IdeaVersionInsertRequest) (*dao.IdeaVersion, error)) *MockIdeaVersionInsertDao_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockManuscriptInsertDao creates a new instance of MockManuscriptInsertDao. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockManuscriptInsertDao(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockManuscriptInsertDao {
	mock := &MockManuscriptInsertDao{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockManuscriptInsertDao is an autogenerated mock type for the ManuscriptInsertDao type
type MockManuscriptInsertDao struct {
	mock.Mock
}

type MockManuscriptInsertDao_Expecter struct {
	mock *mock.Mock
}

func (_m *MockManuscriptInsertDao) EXPECT() *MockManuscriptInsertDao_Expecter {
	return &MockManuscriptInsertDao_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockManuscriptInsertDao
func (_mock *MockManuscriptInsertDao) Exec(ctx context.Context, request *dao.ManuscriptInsertRequest) (*dao.Manuscript, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 *dao.Manuscript
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dao.ManuscriptInsertRequest) (*dao.Manuscript, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dao.ManuscriptInsertRequest) *dao.Manuscript); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dao.Manuscript)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dao.ManuscriptInsertRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockManuscriptInsertDao_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockManuscriptInsertDao_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - request *dao.ManuscriptInsertRequest
func (_e *MockManuscriptInsertDao_Expecter) Exec(ctx any, request any) *MockManuscriptInsertDao_Exec_Call {
	return &MockManuscriptInsertDao_Exec_Call{Call: _e.mock.On("Exec", ctx, request)}
}

func (_c *MockManuscriptInsertDao_Exec_Call) Run(run func(ctx context.Context, request *dao.ManuscriptInsertRequest)) *MockManuscriptInsertDao_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dao.ManuscriptInsertRequest
		if args[1] != nil {
			arg1 = args[1].(*dao.ManuscriptInsertRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockManuscriptInsertDao_Exec_Call) Return(manuscript *dao.Manuscript, err error) *MockManuscriptInsertDao_Exec_Call {
	_c.Call.Return(manuscript, err)
	return _c
}

func (_c *MockManuscriptInsertDao_Exec_Call) RunAndReturn(run func(ctx context.Context, request *dao.ManuscriptInsertRequest) (*dao.Manuscript, error)) *MockManuscriptInsertDao_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockManuscriptHistoryDao creates a new instance of MockManuscriptHistoryDao. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockManuscriptHistoryDao(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockManuscriptHistoryDao {
	mock := &MockManuscriptHistoryDao{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockManuscriptHistoryDao is an autogenerated mock type for the ManuscriptHistoryDao type
type MockManuscriptHistoryDao struct {
	mock.Mock
}

type MockManuscriptHistoryDao_Expecter struct {
	mock *mock.Mock
}

func (_m *MockManuscriptHistoryDao) EXPECT() *MockManuscriptHistoryDao_Expecter {
	return &MockManuscriptHistoryDao_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockManuscriptHistoryDao
func (_mock *MockManuscriptHistoryDao) Exec(ctx context.Context, request *dao.ManuscriptListRequest) ([]*dao.Manuscript, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 []*dao.Manuscript
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dao.ManuscriptListRequest) ([]*dao.Manuscript, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dao.ManuscriptListRequest) []*dao.Manuscript); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*dao.Manuscript)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dao.ManuscriptListRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockManuscriptHistoryDao_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockManuscriptHistoryDao_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - request *dao.ManuscriptListRequest
func (_e *MockManuscriptHistoryDao_Expecter) Exec(ctx any, request any) *MockManuscriptHistoryDao_Exec_Call {
	return &MockManuscriptHistoryDao_Exec_Call{Call: _e.mock.On("Exec", ctx, request)}
}

func (_c *MockManuscriptHistoryDao_Exec_Call) Run(run func(ctx context.Context, request *dao.ManuscriptListRequest)) *MockManuscriptHistoryDao_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dao.ManuscriptListRequest
		if args[1] != nil {
			arg1 = args[1].(*dao.ManuscriptListRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockManuscriptHistoryDao_Exec_Call) Return(manuscripts []*dao.Manuscript, err error) *MockManuscriptHistoryDao_Exec_Call {
	_c.Call.Return(manuscripts, err)
	return _c
}

func (_c *MockManuscriptHistoryDao_Exec_Call) RunAndReturn(run func(ctx context.Context, request *dao.ManuscriptListRequest) ([]*dao.Manuscript, error)) *MockManuscriptHistoryDao_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockProjectSelectDao creates a new instance of MockProjectSelectDao. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProjectSelectDao(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProjectSelectDao {
	mock := &MockProjectSelectDao{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockProjectSelectDao is an autogenerated mock type for the ProjectSelectDao type
type MockProjectSelectDao struct {
	mock.Mock
}

type MockProjectSelectDao_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProjectSelectDao) EXPECT() *MockProjectSelectDao_Expecter {
	return &MockProjectSelectDao_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockProjectSelectDao
func (_mock *MockProjectSelectDao) Exec(ctx context.Context, request *dao.ProjectSelectRequest) (*dao.Project, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 *dao.Project
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dao.ProjectSelectRequest) (*dao.Project, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dao.ProjectSelectRequest) *dao.Project); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dao.Project)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dao.ProjectSelectRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProjectSelectDao_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockProjectSelectDao_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - request *dao.ProjectSelectRequest
func (_e *MockProjectSelectDao_Expecter) Exec(ctx any, request any) *MockProjectSelectDao_Exec_Call {
	return &MockProjectSelectDao_Exec_Call{Call: _e.mock.On("Exec", ctx, request)}
}

func (_c *MockProjectSelectDao_Exec_Call) Run(run func(ctx context.Context, request *dao.ProjectSelectRequest)) *MockProjectSelectDao_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dao.ProjectSelectRequest
		if args[1] != nil {
			arg1 = args[1].(*dao.ProjectSelectRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProjectSelectDao_Exec_Call) Return(project *dao.Project, err error) *MockProjectSelectDao_Exec_Call {
	_c.Call.Return(project, err)
	return _c
}

func (_c *MockProjectSelectDao_Exec_Call) RunAndReturn(run func(ctx context.Context, request *dao.ProjectSelectRequest) (*dao.Project, error)) *MockProjectSelectDao_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockProjectAccessService creates a new instance of MockProjectAccessService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProjectAccessService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProjectAccessService {
	mock := &MockProjectAccessService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockProjectAccessService is an autogenerated mock type for the ProjectAccessService type
type MockProjectAccessService struct {
	mock.Mock
}

type MockProjectAccessService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProjectAccessService) EXPECT() *MockProjectAccessService_Expecter {
	return &MockProjectAccessService_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockProjectAccessService
func (_mock *MockProjectAccessService) Exec(ctx context.Context, request *core.ProjectAccessRequest) (*dao.Project, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 *dao.Project
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *core.ProjectAccessRequest) (*dao.Project, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *core.ProjectAccessRequest) *dao.Project); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dao.Project)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *core.ProjectAccessRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProjectAccessService_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockProjectAccessService_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - request *core.ProjectAccessRequest
func (_e *MockProjectAccessService_Expecter) Exec(ctx any, request any) *MockProjectAccessService_Exec_Call {
	return &MockProjectAccessService_Exec_Call{Call: _e.mock.On("Exec", ctx, request)}
}

func (_c *MockProjectAccessService_Exec_Call) Run(run func(ctx context.Context, request *core.ProjectAccessRequest)) *MockProjectAccessService_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *core.ProjectAccessRequest
		if args[1] != nil {
			arg1 = args[1].(*core.ProjectAccessRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProjectAccessService_Exec_Call) Return(project *dao.Project, err error) *MockProjectAccessService_Exec_Call {
	_c.Call.Return(project, err)
	return _c
}

func (_c *MockProjectAccessService_Exec_Call) RunAndReturn(run func(ctx context.Context, request *core.ProjectAccessRequest) (*dao.Project, error)) *MockProjectAccessService_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockProjectGetIdeaDao creates a new instance of MockProjectGetIdeaDao. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProjectGetIdeaDao(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProjectGetIdeaDao {
	mock := &MockProjectGetIdeaDao{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockProjectGetIdeaDao is an autogenerated mock type for the ProjectGetIdeaDao type
type MockProjectGetIdeaDao struct {
	mock.Mock
}

type MockProjectGetIdeaDao_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProjectGetIdeaDao) EXPECT() *MockProjectGetIdeaDao_Expecter {
	return &MockProjectGetIdeaDao_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockProjectGetIdeaDao
func (_mock *MockProjectGetIdeaDao) Exec(ctx context.Context, request *dao.IdeaSelectRequest) (*dao.Idea, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 *dao.Idea
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dao.IdeaSelectRequest) (*dao.Idea, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dao.IdeaSelectRequest) *dao.Idea); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dao.Idea)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dao.IdeaSelectRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProjectGetIdeaDao_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockProjectGetIdeaDao_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - request *dao.IdeaSelectRequest
func (_e *MockProjectGetIdeaDao_Expecter) Exec(ctx any, request any) *MockProjectGetIdeaDao_Exec_Call {
	return &MockProjectGetIdeaDao_Exec_Call{Call: _e.mock.On("Exec", ctx, request)}
}

func (_c *MockProjectGetIdeaDao_Exec_Call) Run(run func(ctx context.Context, request *dao.IdeaSelectRequest)) *MockProjectGetIdeaDao_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dao.IdeaSelectRequest
		if args[1] != nil {
			arg1 = args[1].(*dao.IdeaSelectRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProjectGetIdeaDao_Exec_Call) Return(idea *dao.Idea, err error) *MockProjectGetIdeaDao_Exec_Call {
	_c.Call.Return(idea, err)
	return _c
}

func (_c *MockProjectGetIdeaDao_Exec_Call) RunAndReturn(run func(ctx context.Context, request *dao.IdeaSelectRequest) (*dao.Idea, error)) *MockProjectGetIdeaDao_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockProjectGetStepValueDao creates a new instance of MockProjectGetStepValueDao. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProjectGetStepValueDao(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProjectGetStepValueDao {
	mock := &MockProjectGetStepValueDao{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockProjectGetStepValueDao is an autogenerated mock type for the ProjectGetStepValueDao type
type MockProjectGetStepValueDao struct {
	mock.Mock
}

type MockProjectGetStepValueDao_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProjectGetStepValueDao) EXPECT() *MockProjectGetStepValueDao_Expecter {
	return &MockProjectGetStepValueDao_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockProjectGetStepValueDao
func (_mock *MockProjectGetStepValueDao) Exec(ctx context.Context, request *dao.StepValueCurrentListRequest) ([]*dao.StepValue, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 []*dao.StepValue
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dao.StepValueCurrentListRequest) ([]*dao.StepValue, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dao.StepValueCurrentListRequest) []*dao.StepValue); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*dao.StepValue)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dao.StepValueCurrentListRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProjectGetStepValueDao_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockProjectGetStepValueDao_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - request *dao.StepValueCurrentListRequest
func (_e *MockProjectGetStepValueDao_Expecter) Exec(ctx any, request any) *MockProjectGetStepValueDao_Exec_Call {
	return &MockProjectGetStepValueDao_Exec_Call{Call: _e.mock.On("Exec", ctx, request)}
}

func (_c *MockProjectGetStepValueDao_Exec_Call) Run(run func(ctx context.Context, request *dao.StepValueCurrentListRequest)) *MockProjectGetStepValueDao_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dao.StepValueCurrentListRequest
		if args[1] != nil {
			arg1 = args[1].(*dao.StepValueCurrentListRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProjectGetStepValueDao_Exec_Call) Return(stepValues []*dao.StepValue, err error) *MockProjectGetStepValueDao_Exec_Call {
	_c.Call.Return(stepValues, err)
	return _c
}

func (_c *MockProjectGetStepValueDao_Exec_Call) RunAndReturn(run func(ctx context.Context, request *dao.StepValueCurrentListRequest) ([]*dao.StepValue, error)) *MockProjectGetStepValueDao_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockProjectGetManuscriptDao creates a new instance of MockProjectGetManuscriptDao. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProjectGetManuscriptDao(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProjectGetManuscriptDao {
	mock := &MockProjectGetManuscriptDao{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockProjectGetManuscriptDao is an autogenerated mock type for the ProjectGetManuscriptDao type
type MockProjectGetManuscriptDao struct {
	mock.Mock
}

type MockProjectGetManuscriptDao_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProjectGetManuscriptDao) EXPECT() *MockProjectGetManuscriptDao_Expecter {
	return &MockProjectGetManuscriptDao_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockProjectGetManuscriptDao
func (_mock *MockProjectGetManuscriptDao) Exec(ctx context.Context, request *dao.ManuscriptSelectRequest) (*dao.Manuscript, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 *dao.Manuscript
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dao.ManuscriptSelectRequest) (*dao.Manuscript, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dao.ManuscriptSelectRequest) *dao.Manuscript); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dao.Manuscript)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dao.ManuscriptSelectRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProjectGetManuscriptDao_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockProjectGetManuscriptDao_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - request *dao.ManuscriptSelectRequest
func (_e *MockProjectGetManuscriptDao_Expecter) Exec(ctx any, request any) *MockProjectGetManuscriptDao_Exec_Call {
	return &MockProjectGetManuscriptDao_Exec_Call{Call: _e.mock.On("Exec", ctx, request)}
}

func (_c *MockProjectGetManuscriptDao_Exec_Call) Run(run func(ctx context.Context, request *dao.ManuscriptSelectRequest)) *MockProjectGetManuscriptDao_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dao.ManuscriptSelectRequest
		if args[1] != nil {
			arg1 = args[1].(*dao.ManuscriptSelectRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProjectGetManuscriptDao_Exec_Call) Return(manuscript *dao.Manuscript, err error) *MockProjectGetManuscriptDao_Exec_Call {
	_c.Call.Return(manuscript, err)
	return _c
}

func (_c *MockProjectGetManuscriptDao_Exec_Call) RunAndReturn(run func(ctx context.Context, request *dao.ManuscriptSelectRequest) (*dao.Manuscript, error)) *MockProjectGetManuscriptDao_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStepValueInsertDao creates a new instance of MockStepValueInsertDao. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStepValueInsertDao(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStepValueInsertDao {
	mock := &MockStepValueInsertDao{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStepValueInsertDao is an autogenerated mock type for the StepValueInsertDao type
type MockStepValueInsertDao struct {
	mock.Mock
}

type MockStepValueInsertDao_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStepValueInsertDao) EXPECT() *MockStepValueInsertDao_Expecter {
	return &MockStepValueInsertDao_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockStepValueInsertDao
func (_mock *MockStepValueInsertDao) Exec(ctx context.Context, request *dao.StepValueInsertRequest) (*dao.StepValue, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 *dao.StepValue
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dao.StepValueInsertRequest) (*dao.StepValue, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dao.StepValueInsertRequest) *dao.StepValue); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dao.StepValue)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dao.StepValueInsertRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStepValueInsertDao_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockStepValueInsertDao_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - request *dao.StepValueInsertRequest
func (_e *MockStepValueInsertDao_Expecter) Exec(ctx any, request any) *MockStepValueInsertDao_Exec_Call {
	return &MockStepValueInsertDao_Exec_Call{Call: _e.mock.On("Exec", ctx, request)}
}

func (_c *MockStepValueInsertDao_Exec_Call) Run(run func(ctx context.Context, request *dao.StepValueInsertRequest)) *MockStepValueInsertDao_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dao.StepValueInsertRequest
		if args[1] != nil {
			arg1 = args[1].(*dao.StepValueInsertRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStepValueInsertDao_Exec_Call) Return(stepValue *dao.StepValue, err error) *MockStepValueInsertDao_Exec_Call {
	_c.Call.Return(stepValue, err)
	return _c
}

func (_c *MockStepValueInsertDao_Exec_Call) RunAndReturn(run func(ctx context.Context, request *dao.StepValueInsertRequest) (*dao.StepValue, error)) *MockStepValueInsertDao_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStepValueHistoryDao creates a new instance of MockStepValueHistoryDao. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStepValueHistoryDao(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStepValueHistoryDao {
	mock := &MockStepValueHistoryDao{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStepValueHistoryDao is an autogenerated mock type for the StepValueHistoryDao type
type MockStepValueHistoryDao struct {
	mock.Mock
}

type MockStepValueHistoryDao_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStepValueHistoryDao) EXPECT() *MockStepValueHistoryDao_Expecter {
	return &MockStepValueHistoryDao_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockStepValueHistoryDao
func (_mock *MockStepValueHistoryDao) Exec(ctx context.Context, request *dao.StepValueListRequest) ([]*dao.StepValue, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 []*dao.StepValue
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dao.StepValueListRequest) ([]*dao.StepValue, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dao.StepValueListRequest) []*dao.StepValue); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*dao.StepValue)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dao.StepValueListRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStepValueHistoryDao_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockStepValueHistoryDao_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - request *dao.StepValueListRequest
func (_e *MockStepValueHistoryDao_Expecter) Exec(ctx any, request any) *MockStepValueHistoryDao_Exec_Call {
	return &MockStepValueHistoryDao_Exec_Call{Call: _e.mock.On("Exec", ctx, request)}
}

func (_c *MockStepValueHistoryDao_Exec_Call) Run(run func(ctx context.Context, request *dao.StepValueListRequest)) *MockStepValueHistoryDao_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dao.StepValueListRequest
		if args[1] != nil {
			arg1 = args[1].(*dao.StepValueListRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStepValueHistoryDao_Exec_Call) Return(stepValues []*dao.StepValue, err error) *MockStepValueHistoryDao_Exec_Call {
	_c.Call.Return(stepValues, err)
	return _c
}

func (_c *MockStepValueHistoryDao_Exec_Call) RunAndReturn(run func(ctx context.Context, request *dao.StepValueListRequest) ([]*dao.StepValue, error)) *MockStepValueHistoryDao_Exec_Call {
	_c.Call.Return(run)
	return _c
}
