// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package coremocks

import (
	"context"
	"encoding/json"

	"github.com/a-novel/service-jobs/pkg/go"
	"github.com/a-novel/service-narrative-engine/internal/core"
	"github.com/a-novel/service-narrative-engine/internal/dao"
	mock "github.com/stretchr/testify/mock"
	"google.golang.org/grpc"
)

// NewMockItemCreateDao creates a new instance of MockItemCreateDao. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockItemCreateDao(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockItemCreateDao {
	mock := &MockItemCreateDao{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockItemCreateDao is an autogenerated mock type for the ItemCreateDao type
type MockItemCreateDao struct {
	mock.Mock
}

type MockItemCreateDao_Expecter struct {
	mock *mock.Mock
}

func (_m *MockItemCreateDao) EXPECT() *MockItemCreateDao_Expecter {
	return &MockItemCreateDao_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockItemCreateDao
func (_mock *MockItemCreateDao) Exec(ctx context.Context, request *dao.ItemCreateRequest) (*dao.Item, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 *dao.Item
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dao.ItemCreateRequest) (*dao.Item, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dao.ItemCreateRequest) *dao.Item); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dao.Item)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dao.ItemCreateRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockItemCreateDao_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockItemCreateDao_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - request *dao.ItemCreateRequest
func (_e *MockItemCreateDao_Expecter) Exec(ctx any, request any) *MockItemCreateDao_Exec_Call {
	return &MockItemCreateDao_Exec_Call{Call: _e.mock.On("Exec", ctx, request)}
}

func (_c *MockItemCreateDao_Exec_Call) Run(run func(ctx context.Context, request *dao.ItemCreateRequest)) *MockItemCreateDao_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dao.ItemCreateRequest
		if args[1] != nil {
			arg1 = args[1].(*dao.ItemCreateRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockItemCreateDao_Exec_Call) Return(item *dao.Item, err error) *MockItemCreateDao_Exec_Call {
	_c.Call.Return(item, err)
	return _c
}

func (_c *MockItemCreateDao_Exec_Call) RunAndReturn(run func(ctx context.Context, request *dao.ItemCreateRequest) (*dao.Item, error)) *MockItemCreateDao_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockItemDeleteDao creates a new instance of MockItemDeleteDao. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockItemDeleteDao(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockItemDeleteDao {
	mock := &MockItemDeleteDao{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockItemDeleteDao is an autogenerated mock type for the ItemDeleteDao type
type MockItemDeleteDao struct {
	mock.Mock
}

type MockItemDeleteDao_Expecter struct {
	mock *mock.Mock
}

func (_m *MockItemDeleteDao) EXPECT() *MockItemDeleteDao_Expecter {
	return &MockItemDeleteDao_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockItemDeleteDao
func (_mock *MockItemDeleteDao) Exec(ctx context.Context, request *dao.ItemDeleteRequest) (*dao.Item, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 *dao.Item
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dao.ItemDeleteRequest) (*dao.Item, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dao.ItemDeleteRequest) *dao.Item); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dao.Item)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dao.ItemDeleteRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockItemDeleteDao_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockItemDeleteDao_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - request *dao.ItemDeleteRequest
func (_e *MockItemDeleteDao_Expecter) Exec(ctx any, request any) *MockItemDeleteDao_Exec_Call {
	return &MockItemDeleteDao_Exec_Call{Call: _e.mock.On("Exec", ctx, request)}
}

func (_c *MockItemDeleteDao_Exec_Call) Run(run func(ctx context.Context, request *dao.ItemDeleteRequest)) *MockItemDeleteDao_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dao.ItemDeleteRequest
		if args[1] != nil {
			arg1 = args[1].(*dao.ItemDeleteRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockItemDeleteDao_Exec_Call) Return(item *dao.Item, err error) *MockItemDeleteDao_Exec_Call {
	_c.Call.Return(item, err)
	return _c
}

func (_c *MockItemDeleteDao_Exec_Call) RunAndReturn(run func(ctx context.Context, request *dao.ItemDeleteRequest) (*dao.Item, error)) *MockItemDeleteDao_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockItemGetDao creates a new instance of MockItemGetDao. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockItemGetDao(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockItemGetDao {
	mock := &MockItemGetDao{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockItemGetDao is an autogenerated mock type for the ItemGetDao type
type MockItemGetDao struct {
	mock.Mock
}

type MockItemGetDao_Expecter struct {
	mock *mock.Mock
}

func (_m *MockItemGetDao) EXPECT() *MockItemGetDao_Expecter {
	return &MockItemGetDao_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockItemGetDao
func (_mock *MockItemGetDao) Exec(ctx context.Context, request *dao.ItemGetRequest) (*dao.Item, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 *dao.Item
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dao.ItemGetRequest) (*dao.Item, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dao.ItemGetRequest) *dao.Item); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dao.Item)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dao.ItemGetRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockItemGetDao_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockItemGetDao_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - request *dao.ItemGetRequest
func (_e *MockItemGetDao_Expecter) Exec(ctx any, request any) *MockItemGetDao_Exec_Call {
	return &MockItemGetDao_Exec_Call{Call: _e.mock.On("Exec", ctx, request)}
}

func (_c *MockItemGetDao_Exec_Call) Run(run func(ctx context.Context, request *dao.ItemGetRequest)) *MockItemGetDao_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dao.ItemGetRequest
		if args[1] != nil {
			arg1 = args[1].(*dao.ItemGetRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockItemGetDao_Exec_Call) Return(item *dao.Item, err error) *MockItemGetDao_Exec_Call {
	_c.Call.Return(item, err)
	return _c
}

func (_c *MockItemGetDao_Exec_Call) RunAndReturn(run func(ctx context.Context, request *dao.ItemGetRequest) (*dao.Item, error)) *MockItemGetDao_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockItemListDao creates a new instance of MockItemListDao. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockItemListDao(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockItemListDao {
	mock := &MockItemListDao{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockItemListDao is an autogenerated mock type for the ItemListDao type
type MockItemListDao struct {
	mock.Mock
}

type MockItemListDao_Expecter struct {
	mock *mock.Mock
}

func (_m *MockItemListDao) EXPECT() *MockItemListDao_Expecter {
	return &MockItemListDao_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockItemListDao
func (_mock *MockItemListDao) Exec(ctx context.Context, request *dao.ItemListRequest) ([]*dao.Item, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 []*dao.Item
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dao.ItemListRequest) ([]*dao.Item, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dao.ItemListRequest) []*dao.Item); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*dao.Item)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dao.ItemListRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockItemListDao_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockItemListDao_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - request *dao.ItemListRequest
func (_e *MockItemListDao_Expecter) Exec(ctx any, request any) *MockItemListDao_Exec_Call {
	return &MockItemListDao_Exec_Call{Call: _e.mock.On("Exec", ctx, request)}
}

func (_c *MockItemListDao_Exec_Call) Run(run func(ctx context.Context, request *dao.ItemListRequest)) *MockItemListDao_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dao.ItemListRequest
		if args[1] != nil {
			arg1 = args[1].(*dao.ItemListRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockItemListDao_Exec_Call) Return(items []*dao.Item, err error) *MockItemListDao_Exec_Call {
	_c.Call.Return(items, err)
	return _c
}

func (_c *MockItemListDao_Exec_Call) RunAndReturn(run func(ctx context.Context, request *dao.ItemListRequest) ([]*dao.Item, error)) *MockItemListDao_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockItemUpdateDao creates a new instance of MockItemUpdateDao. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockItemUpdateDao(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockItemUpdateDao {
	mock := &MockItemUpdateDao{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockItemUpdateDao is an autogenerated mock type for the ItemUpdateDao type
type MockItemUpdateDao struct {
	mock.Mock
}

type MockItemUpdateDao_Expecter struct {
	mock *mock.Mock
}

func (_m *MockItemUpdateDao) EXPECT() *MockItemUpdateDao_Expecter {
	return &MockItemUpdateDao_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockItemUpdateDao
func (_mock *MockItemUpdateDao) Exec(ctx context.Context, request *dao.ItemUpdateRequest) (*dao.Item, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 *dao.Item
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dao.ItemUpdateRequest) (*dao.Item, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dao.ItemUpdateRequest) *dao.Item); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dao.Item)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dao.ItemUpdateRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockItemUpdateDao_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockItemUpdateDao_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - request *dao.ItemUpdateRequest
func (_e *MockItemUpdateDao_Expecter) Exec(ctx any, request any) *MockItemUpdateDao_Exec_Call {
	return &MockItemUpdateDao_Exec_Call{Call: _e.mock.On("Exec", ctx, request)}
}

func (_c *MockItemUpdateDao_Exec_Call) Run(run func(ctx context.Context, request *dao.ItemUpdateRequest)) *MockItemUpdateDao_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dao.ItemUpdateRequest
		if args[1] != nil {
			arg1 = args[1].(*dao.ItemUpdateRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockItemUpdateDao_Exec_Call) Return(item *dao.Item, err error) *MockItemUpdateDao_Exec_Call {
	_c.Call.Return(item, err)
	return _c
}

func (_c *MockItemUpdateDao_Exec_Call) RunAndReturn(run func(ctx context.Context, request *dao.ItemUpdateRequest) (*dao.Item, error)) *MockItemUpdateDao_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockJobEnqueueService creates a new instance of MockJobEnqueueService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockJobEnqueueService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockJobEnqueueService {
	mock := &MockJobEnqueueService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockJobEnqueueService is an autogenerated mock type for the JobEnqueueService type
type MockJobEnqueueService struct {
	mock.Mock
}

type MockJobEnqueueService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockJobEnqueueService) EXPECT() *MockJobEnqueueService_Expecter {
	return &MockJobEnqueueService_Expecter{mock: &_m.Mock}
}

// JobEnqueue provides a mock function for the type MockJobEnqueueService
func (_mock *MockJobEnqueueService) JobEnqueue(ctx context.Context, request *servicejobs.JobEnqueueRequest, opts ...grpc.CallOption) (*servicejobs.JobEnqueueResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, request, opts)
	} else {
		tmpRet = _mock.Called(ctx, request)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for JobEnqueue")
	}

	var r0 *servicejobs.JobEnqueueResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *servicejobs.JobEnqueueRequest, ...grpc.CallOption) (*servicejobs.JobEnqueueResponse, error)); ok {
		return returnFunc(ctx, request, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *servicejobs.JobEnqueueRequest, ...grpc.CallOption) *servicejobs.JobEnqueueResponse); ok {
		r0 = returnFunc(ctx, request, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*servicejobs.JobEnqueueResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *servicejobs.JobEnqueueRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, request, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockJobEnqueueService_JobEnqueue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'JobEnqueue'
type MockJobEnqueueService_JobEnqueue_Call struct {
	*mock.Call
}

// JobEnqueue is a helper method to define mock.On call
//   - ctx context.Context
//   - request *servicejobs.JobEnqueueRequest
//   - opts ...grpc.CallOption
func (_e *MockJobEnqueueService_Expecter) JobEnqueue(ctx any, request any, opts ...any) *MockJobEnqueueService_JobEnqueue_Call {
	return &MockJobEnqueueService_JobEnqueue_Call{Call: _e.mock.On("JobEnqueue",
		append([]any{ctx, request}, opts...)...)}
}

func (_c *MockJobEnqueueService_JobEnqueue_Call) Run(run func(ctx context.Context, request *servicejobs.JobEnqueueRequest, opts ...grpc.CallOption)) *MockJobEnqueueService_JobEnqueue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *servicejobs.JobEnqueueRequest
		if args[1] != nil {
			arg1 = args[1].(*servicejobs.JobEnqueueRequest)
		}
		var arg2 []grpc.CallOption
		var variadicArgs []grpc.CallOption
		if len(args) > 2 {
			variadicArgs = args[2].([]grpc.CallOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockJobEnqueueService_JobEnqueue_Call) Return(v *servicejobs.JobEnqueueResponse, err error) *MockJobEnqueueService_JobEnqueue_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockJobEnqueueService_JobEnqueue_Call) RunAndReturn(run func(ctx context.Context, request *servicejobs.JobEnqueueRequest, opts ...grpc.CallOption) (*servicejobs.JobEnqueueResponse, error)) *MockJobEnqueueService_JobEnqueue_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockJobExecuteServiceSettle creates a new instance of MockJobExecuteServiceSettle. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockJobExecuteServiceSettle(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockJobExecuteServiceSettle {
	mock := &MockJobExecuteServiceSettle{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockJobExecuteServiceSettle is an autogenerated mock type for the JobExecuteServiceSettle type
type MockJobExecuteServiceSettle struct {
	mock.Mock
}

type MockJobExecuteServiceSettle_Expecter struct {
	mock *mock.Mock
}

func (_m *MockJobExecuteServiceSettle) EXPECT() *MockJobExecuteServiceSettle_Expecter {
	return &MockJobExecuteServiceSettle_Expecter{mock: &_m.Mock}
}

// JobSettle provides a mock function for the type MockJobExecuteServiceSettle
func (_mock *MockJobExecuteServiceSettle) JobSettle(ctx context.Context, request *servicejobs.JobSettleRequest, opts ...grpc.CallOption) (*servicejobs.JobSettleResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, request, opts)
	} else {
		tmpRet = _mock.Called(ctx, request)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for JobSettle")
	}

	var r0 *servicejobs.JobSettleResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *servicejobs.JobSettleRequest, ...grpc.CallOption) (*servicejobs.JobSettleResponse, error)); ok {
		return returnFunc(ctx, request, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *servicejobs.JobSettleRequest, ...grpc.CallOption) *servicejobs.JobSettleResponse); ok {
		r0 = returnFunc(ctx, request, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*servicejobs.JobSettleResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *servicejobs.JobSettleRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, request, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockJobExecuteServiceSettle_JobSettle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'JobSettle'
type MockJobExecuteServiceSettle_JobSettle_Call struct {
	*mock.Call
}

// JobSettle is a helper method to define mock.On call
//   - ctx context.Context
//   - request *servicejobs.JobSettleRequest
//   - opts ...grpc.CallOption
func (_e *MockJobExecuteServiceSettle_Expecter) JobSettle(ctx any, request any, opts ...any) *MockJobExecuteServiceSettle_JobSettle_Call {
	return &MockJobExecuteServiceSettle_JobSettle_Call{Call: _e.mock.On("JobSettle",
		append([]any{ctx, request}, opts...)...)}
}

func (_c *MockJobExecuteServiceSettle_JobSettle_Call) Run(run func(ctx context.Context, request *servicejobs.JobSettleRequest, opts ...grpc.CallOption)) *MockJobExecuteServiceSettle_JobSettle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *servicejobs.JobSettleRequest
		if args[1] != nil {
			arg1 = args[1].(*servicejobs.JobSettleRequest)
		}
		var arg2 []grpc.CallOption
		var variadicArgs []grpc.CallOption
		if len(args) > 2 {
			variadicArgs = args[2].([]grpc.CallOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockJobExecuteServiceSettle_JobSettle_Call) Return(v *servicejobs.JobSettleResponse, err error) *MockJobExecuteServiceSettle_JobSettle_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockJobExecuteServiceSettle_JobSettle_Call) RunAndReturn(run func(ctx context.Context, request *servicejobs.JobSettleRequest, opts ...grpc.CallOption) (*servicejobs.JobSettleResponse, error)) *MockJobExecuteServiceSettle_JobSettle_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockJobExecuteServiceRecordProviderCall creates a new instance of MockJobExecuteServiceRecordProviderCall. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockJobExecuteServiceRecordProviderCall(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockJobExecuteServiceRecordProviderCall {
	mock := &MockJobExecuteServiceRecordProviderCall{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockJobExecuteServiceRecordProviderCall is an autogenerated mock type for the JobExecuteServiceRecordProviderCall type
type MockJobExecuteServiceRecordProviderCall struct {
	mock.Mock
}

type MockJobExecuteServiceRecordProviderCall_Expecter struct {
	mock *mock.Mock
}

func (_m *MockJobExecuteServiceRecordProviderCall) EXPECT() *MockJobExecuteServiceRecordProviderCall_Expecter {
	return &MockJobExecuteServiceRecordProviderCall_Expecter{mock: &_m.Mock}
}

// JobRecordProviderCall provides a mock function for the type MockJobExecuteServiceRecordProviderCall
func (_mock *MockJobExecuteServiceRecordProviderCall) JobRecordProviderCall(ctx context.Context, request *servicejobs.JobRecordProviderCallRequest, opts ...grpc.CallOption) (*servicejobs.JobRecordProviderCallResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, request, opts)
	} else {
		tmpRet = _mock.Called(ctx, request)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for JobRecordProviderCall")
	}

	var r0 *servicejobs.JobRecordProviderCallResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *servicejobs.JobRecordProviderCallRequest, ...grpc.CallOption) (*servicejobs.JobRecordProviderCallResponse, error)); ok {
		return returnFunc(ctx, request, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *servicejobs.JobRecordProviderCallRequest, ...grpc.CallOption) *servicejobs.JobRecordProviderCallResponse); ok {
		r0 = returnFunc(ctx, request, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*servicejobs.JobRecordProviderCallResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *servicejobs.JobRecordProviderCallRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, request, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockJobExecuteServiceRecordProviderCall_JobRecordProviderCall_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'JobRecordProviderCall'
type MockJobExecuteServiceRecordProviderCall_JobRecordProviderCall_Call struct {
	*mock.Call
}

// JobRecordProviderCall is a helper method to define mock.On call
//   - ctx context.Context
//   - request *servicejobs.JobRecordProviderCallRequest
//   - opts ...grpc.CallOption
func (_e *MockJobExecuteServiceRecordProviderCall_Expecter) JobRecordProviderCall(ctx any, request any, opts ...any) *MockJobExecuteServiceRecordProviderCall_JobRecordProviderCall_Call {
	return &MockJobExecuteServiceRecordProviderCall_JobRecordProviderCall_Call{Call: _e.mock.On("JobRecordProviderCall",
		append([]any{ctx, request}, opts...)...)}
}

func (_c *MockJobExecuteServiceRecordProviderCall_JobRecordProviderCall_Call) Run(run func(ctx context.Context, request *servicejobs.JobRecordProviderCallRequest, opts ...grpc.CallOption)) *MockJobExecuteServiceRecordProviderCall_JobRecordProviderCall_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *servicejobs.JobRecordProviderCallRequest
		if args[1] != nil {
			arg1 = args[1].(*servicejobs.JobRecordProviderCallRequest)
		}
		var arg2 []grpc.CallOption
		var variadicArgs []grpc.CallOption
		if len(args) > 2 {
			variadicArgs = args[2].([]grpc.CallOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockJobExecuteServiceRecordProviderCall_JobRecordProviderCall_Call) Return(v *servicejobs.JobRecordProviderCallResponse, err error) *MockJobExecuteServiceRecordProviderCall_JobRecordProviderCall_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockJobExecuteServiceRecordProviderCall_JobRecordProviderCall_Call) RunAndReturn(run func(ctx context.Context, request *servicejobs.JobRecordProviderCallRequest, opts ...grpc.CallOption) (*servicejobs.JobRecordProviderCallResponse, error)) *MockJobExecuteServiceRecordProviderCall_JobRecordProviderCall_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockJobExecuteLogger creates a new instance of MockJobExecuteLogger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockJobExecuteLogger(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockJobExecuteLogger {
	mock := &MockJobExecuteLogger{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockJobExecuteLogger is an autogenerated mock type for the JobExecuteLogger type
type MockJobExecuteLogger struct {
	mock.Mock
}

type MockJobExecuteLogger_Expecter struct {
	mock *mock.Mock
}

func (_m *MockJobExecuteLogger) EXPECT() *MockJobExecuteLogger_Expecter {
	return &MockJobExecuteLogger_Expecter{mock: &_m.Mock}
}

// Err provides a mock function for the type MockJobExecuteLogger
func (_mock *MockJobExecuteLogger) Err(ctx context.Context, message string, fields ...any) {
	if len(fields) > 0 {
		_mock.Called(ctx, message, fields)
	} else {
		_mock.Called(ctx, message)
	}

	return
}

// MockJobExecuteLogger_Err_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Err'
type MockJobExecuteLogger_Err_Call struct {
	*mock.Call
}

// Err is a helper method to define mock.On call
//   - ctx context.Context
//   - message string
//   - fields ...any
func (_e *MockJobExecuteLogger_Expecter) Err(ctx any, message any, fields ...any) *MockJobExecuteLogger_Err_Call {
	return &MockJobExecuteLogger_Err_Call{Call: _e.mock.On("Err",
		append([]any{ctx, message}, fields...)...)}
}

func (_c *MockJobExecuteLogger_Err_Call) Run(run func(ctx context.Context, message string, fields ...any)) *MockJobExecuteLogger_Err_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []any
		var variadicArgs []any
		if len(args) > 2 {
			variadicArgs = args[2].([]any)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockJobExecuteLogger_Err_Call) Return() *MockJobExecuteLogger_Err_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockJobExecuteLogger_Err_Call) RunAndReturn(run func(ctx context.Context, message string, fields ...any)) *MockJobExecuteLogger_Err_Call {
	_c.Run(run)
	return _c
}

// NewMockJobGetService creates a new instance of MockJobGetService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockJobGetService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockJobGetService {
	mock := &MockJobGetService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockJobGetService is an autogenerated mock type for the JobGetService type
type MockJobGetService struct {
	mock.Mock
}

type MockJobGetService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockJobGetService) EXPECT() *MockJobGetService_Expecter {
	return &MockJobGetService_Expecter{mock: &_m.Mock}
}

// JobGet provides a mock function for the type MockJobGetService
func (_mock *MockJobGetService) JobGet(ctx context.Context, request *servicejobs.JobGetRequest, opts ...grpc.CallOption) (*servicejobs.JobGetResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, request, opts)
	} else {
		tmpRet = _mock.Called(ctx, request)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for JobGet")
	}

	var r0 *servicejobs.JobGetResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *servicejobs.JobGetRequest, ...grpc.CallOption) (*servicejobs.JobGetResponse, error)); ok {
		return returnFunc(ctx, request, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *servicejobs.JobGetRequest, ...grpc.CallOption) *servicejobs.JobGetResponse); ok {
		r0 = returnFunc(ctx, request, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*servicejobs.JobGetResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *servicejobs.JobGetRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, request, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockJobGetService_JobGet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'JobGet'
type MockJobGetService_JobGet_Call struct {
	*mock.Call
}

// JobGet is a helper method to define mock.On call
//   - ctx context.Context
//   - request *servicejobs.JobGetRequest
//   - opts ...grpc.CallOption
func (_e *MockJobGetService_Expecter) JobGet(ctx any, request any, opts ...any) *MockJobGetService_JobGet_Call {
	return &MockJobGetService_JobGet_Call{Call: _e.mock.On("JobGet",
		append([]any{ctx, request}, opts...)...)}
}

func (_c *MockJobGetService_JobGet_Call) Run(run func(ctx context.Context, request *servicejobs.JobGetRequest, opts ...grpc.CallOption)) *MockJobGetService_JobGet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *servicejobs.JobGetRequest
		if args[1] != nil {
			arg1 = args[1].(*servicejobs.JobGetRequest)
		}
		var arg2 []grpc.CallOption
		var variadicArgs []grpc.CallOption
		if len(args) > 2 {
			variadicArgs = args[2].([]grpc.CallOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockJobGetService_JobGet_Call) Return(v *servicejobs.JobGetResponse, err error) *MockJobGetService_JobGet_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockJobGetService_JobGet_Call) RunAndReturn(run func(ctx context.Context, request *servicejobs.JobGetRequest, opts ...grpc.CallOption) (*servicejobs.JobGetResponse, error)) *MockJobGetService_JobGet_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockJobHandler creates a new instance of MockJobHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockJobHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockJobHandler {
	mock := &MockJobHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockJobHandler is an autogenerated mock type for the JobHandler type
type MockJobHandler struct {
	mock.Mock
}

type MockJobHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockJobHandler) EXPECT() *MockJobHandler_Expecter {
	return &MockJobHandler_Expecter{mock: &_m.Mock}
}

// Handle provides a mock function for the type MockJobHandler
func (_mock *MockJobHandler) Handle(ctx context.Context, job *core.Job, recorder core.ProviderCallRecorder) (json.RawMessage, error) {
	ret := _mock.Called(ctx, job, recorder)

	if len(ret) == 0 {
		panic("no return value specified for Handle")
	}

	var r0 json.RawMessage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *core.Job, core.ProviderCallRecorder) (json.RawMessage, error)); ok {
		return returnFunc(ctx, job, recorder)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *core.Job, core.ProviderCallRecorder) json.RawMessage); ok {
		r0 = returnFunc(ctx, job, recorder)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(json.RawMessage)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *core.Job, core.ProviderCallRecorder) error); ok {
		r1 = returnFunc(ctx, job, recorder)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockJobHandler_Handle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Handle'
type MockJobHandler_Handle_Call struct {
	*mock.Call
}

// Handle is a helper method to define mock.On call
//   - ctx context.Context
//   - job *core.Job
//   - recorder core.ProviderCallRecorder
func (_e *MockJobHandler_Expecter) Handle(ctx any, job any, recorder any) *MockJobHandler_Handle_Call {
	return &MockJobHandler_Handle_Call{Call: _e.mock.On("Handle", ctx, job, recorder)}
}

func (_c *MockJobHandler_Handle_Call) Run(run func(ctx context.Context, job *core.Job, recorder core.ProviderCallRecorder)) *MockJobHandler_Handle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *core.Job
		if args[1] != nil {
			arg1 = args[1].(*core.Job)
		}
		var arg2 core.ProviderCallRecorder
		if args[2] != nil {
			arg2 = args[2].(core.ProviderCallRecorder)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockJobHandler_Handle_Call) Return(rawMessage json.RawMessage, err error) *MockJobHandler_Handle_Call {
	_c.Call.Return(rawMessage, err)
	return _c
}

func (_c *MockJobHandler_Handle_Call) RunAndReturn(run func(ctx context.Context, job *core.Job, recorder core.ProviderCallRecorder) (json.RawMessage, error)) *MockJobHandler_Handle_Call {
	_c.Call.Return(run)
	return _c
}

// Kind provides a mock function for the type MockJobHandler
func (_mock *MockJobHandler) Kind() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Kind")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockJobHandler_Kind_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Kind'
type MockJobHandler_Kind_Call struct {
	*mock.Call
}

// Kind is a helper method to define mock.On call
func (_e *MockJobHandler_Expecter) Kind() *MockJobHandler_Kind_Call {
	return &MockJobHandler_Kind_Call{Call: _e.mock.On("Kind")}
}

func (_c *MockJobHandler_Kind_Call) Run(run func()) *MockJobHandler_Kind_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockJobHandler_Kind_Call) Return(s string) *MockJobHandler_Kind_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockJobHandler_Kind_Call) RunAndReturn(run func() string) *MockJobHandler_Kind_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockProviderCallRecorder creates a new instance of MockProviderCallRecorder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProviderCallRecorder(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProviderCallRecorder {
	mock := &MockProviderCallRecorder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockProviderCallRecorder is an autogenerated mock type for the ProviderCallRecorder type
type MockProviderCallRecorder struct {
	mock.Mock
}

type MockProviderCallRecorder_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProviderCallRecorder) EXPECT() *MockProviderCallRecorder_Expecter {
	return &MockProviderCallRecorder_Expecter{mock: &_m.Mock}
}

// Record provides a mock function for the type MockProviderCallRecorder
func (_mock *MockProviderCallRecorder) Record(ctx context.Context, providerCallID string) error {
	ret := _mock.Called(ctx, providerCallID)

	if len(ret) == 0 {
		panic("no return value specified for Record")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, providerCallID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockProviderCallRecorder_Record_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Record'
type MockProviderCallRecorder_Record_Call struct {
	*mock.Call
}

// Record is a helper method to define mock.On call
//   - ctx context.Context
//   - providerCallID string
func (_e *MockProviderCallRecorder_Expecter) Record(ctx any, providerCallID any) *MockProviderCallRecorder_Record_Call {
	return &MockProviderCallRecorder_Record_Call{Call: _e.mock.On("Record", ctx, providerCallID)}
}

func (_c *MockProviderCallRecorder_Record_Call) Run(run func(ctx context.Context, providerCallID string)) *MockProviderCallRecorder_Record_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProviderCallRecorder_Record_Call) Return(err error) *MockProviderCallRecorder_Record_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockProviderCallRecorder_Record_Call) RunAndReturn(run func(ctx context.Context, providerCallID string) error) *MockProviderCallRecorder_Record_Call {
	_c.Call.Return(run)
	return _c
}
