// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package coremocks

import (
	"context"

	"github.com/a-novel/service-narrative-engine/internal/core"
	"github.com/a-novel/service-narrative-engine/internal/dao"
	"github.com/a-novel/service-narrative-engine/internal/lib"
	mock "github.com/stretchr/testify/mock"
)

// NewMockGenerationGetGateway creates a new instance of MockGenerationGetGateway. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGenerationGetGateway(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGenerationGetGateway {
	mock := &MockGenerationGetGateway{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockGenerationGetGateway is an autogenerated mock type for the GenerationGetGateway type
type MockGenerationGetGateway struct {
	mock.Mock
}

type MockGenerationGetGateway_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGenerationGetGateway) EXPECT() *MockGenerationGetGateway_Expecter {
	return &MockGenerationGetGateway_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockGenerationGetGateway
func (_mock *MockGenerationGetGateway) Exec(ctx context.Context, request *lib.GenerationGetGatewayRequest) (*lib.Generation, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 *lib.Generation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *lib.GenerationGetGatewayRequest) (*lib.Generation, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *lib.GenerationGetGatewayRequest) *lib.Generation); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*lib.Generation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *lib.GenerationGetGatewayRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGenerationGetGateway_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockGenerationGetGateway_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - request *lib.GenerationGetGatewayRequest
func (_e *MockGenerationGetGateway_Expecter) Exec(ctx any, request any) *MockGenerationGetGateway_Exec_Call {
	return &MockGenerationGetGateway_Exec_Call{Call: _e.mock.On("Exec", ctx, request)}
}

func (_c *MockGenerationGetGateway_Exec_Call) Run(run func(ctx context.Context, request *lib.GenerationGetGatewayRequest)) *MockGenerationGetGateway_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *lib.GenerationGetGatewayRequest
		if args[1] != nil {
			arg1 = args[1].(*lib.GenerationGetGatewayRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGenerationGetGateway_Exec_Call) Return(generation *lib.Generation, err error) *MockGenerationGetGateway_Exec_Call {
	_c.Call.Return(generation, err)
	return _c
}

func (_c *MockGenerationGetGateway_Exec_Call) RunAndReturn(run func(ctx context.Context, request *lib.GenerationGetGatewayRequest) (*lib.Generation, error)) *MockGenerationGetGateway_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGenerationSubmitGateway creates a new instance of MockGenerationSubmitGateway. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGenerationSubmitGateway(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGenerationSubmitGateway {
	mock := &MockGenerationSubmitGateway{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockGenerationSubmitGateway is an autogenerated mock type for the GenerationSubmitGateway type
type MockGenerationSubmitGateway struct {
	mock.Mock
}

type MockGenerationSubmitGateway_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGenerationSubmitGateway) EXPECT() *MockGenerationSubmitGateway_Expecter {
	return &MockGenerationSubmitGateway_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockGenerationSubmitGateway
func (_mock *MockGenerationSubmitGateway) Exec(ctx context.Context, request *lib.GenerationSubmitGatewayRequest) (*lib.GenerationSubmitGatewayResult, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 *lib.GenerationSubmitGatewayResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *lib.GenerationSubmitGatewayRequest) (*lib.GenerationSubmitGatewayResult, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *lib.GenerationSubmitGatewayRequest) *lib.GenerationSubmitGatewayResult); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*lib.GenerationSubmitGatewayResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *lib.GenerationSubmitGatewayRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGenerationSubmitGateway_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockGenerationSubmitGateway_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - request *lib.GenerationSubmitGatewayRequest
func (_e *MockGenerationSubmitGateway_Expecter) Exec(ctx any, request any) *MockGenerationSubmitGateway_Exec_Call {
	return &MockGenerationSubmitGateway_Exec_Call{Call: _e.mock.On("Exec", ctx, request)}
}

func (_c *MockGenerationSubmitGateway_Exec_Call) Run(run func(ctx context.Context, request *lib.GenerationSubmitGatewayRequest)) *MockGenerationSubmitGateway_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *lib.GenerationSubmitGatewayRequest
		if args[1] != nil {
			arg1 = args[1].(*lib.GenerationSubmitGatewayRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGenerationSubmitGateway_Exec_Call) Return(generationSubmitGatewayResult *lib.GenerationSubmitGatewayResult, err error) *MockGenerationSubmitGateway_Exec_Call {
	_c.Call.Return(generationSubmitGatewayResult, err)
	return _c
}

func (_c *MockGenerationSubmitGateway_Exec_Call) RunAndReturn(run func(ctx context.Context, request *lib.GenerationSubmitGatewayRequest) (*lib.GenerationSubmitGatewayResult, error)) *MockGenerationSubmitGateway_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGenerationWatchGateway creates a new instance of MockGenerationWatchGateway. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGenerationWatchGateway(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGenerationWatchGateway {
	mock := &MockGenerationWatchGateway{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockGenerationWatchGateway is an autogenerated mock type for the GenerationWatchGateway type
type MockGenerationWatchGateway struct {
	mock.Mock
}

type MockGenerationWatchGateway_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGenerationWatchGateway) EXPECT() *MockGenerationWatchGateway_Expecter {
	return &MockGenerationWatchGateway_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockGenerationWatchGateway
func (_mock *MockGenerationWatchGateway) Exec(ctx context.Context, request *lib.GenerationWatchGatewayRequest) (lib.GenerationWatchGatewayStream, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 lib.GenerationWatchGatewayStream
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *lib.GenerationWatchGatewayRequest) (lib.GenerationWatchGatewayStream, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *lib.GenerationWatchGatewayRequest) lib.GenerationWatchGatewayStream); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(lib.GenerationWatchGatewayStream)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *lib.GenerationWatchGatewayRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGenerationWatchGateway_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockGenerationWatchGateway_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - request *lib.GenerationWatchGatewayRequest
func (_e *MockGenerationWatchGateway_Expecter) Exec(ctx any, request any) *MockGenerationWatchGateway_Exec_Call {
	return &MockGenerationWatchGateway_Exec_Call{Call: _e.mock.On("Exec", ctx, request)}
}

func (_c *MockGenerationWatchGateway_Exec_Call) Run(run func(ctx context.Context, request *lib.GenerationWatchGatewayRequest)) *MockGenerationWatchGateway_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *lib.GenerationWatchGatewayRequest
		if args[1] != nil {
			arg1 = args[1].(*lib.GenerationWatchGatewayRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGenerationWatchGateway_Exec_Call) Return(generationWatchGatewayStream lib.GenerationWatchGatewayStream, err error) *MockGenerationWatchGateway_Exec_Call {
	_c.Call.Return(generationWatchGatewayStream, err)
	return _c
}

func (_c *MockGenerationWatchGateway_Exec_Call) RunAndReturn(run func(ctx context.Context, request *lib.GenerationWatchGatewayRequest) (lib.GenerationWatchGatewayStream, error)) *MockGenerationWatchGateway_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIdeaCreateDao creates a new instance of MockIdeaCreateDao. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIdeaCreateDao(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIdeaCreateDao {
	mock := &MockIdeaCreateDao{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIdeaCreateDao is an autogenerated mock type for the IdeaCreateDao type
type MockIdeaCreateDao struct {
	mock.Mock
}

type MockIdeaCreateDao_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIdeaCreateDao) EXPECT() *MockIdeaCreateDao_Expecter {
	return &MockIdeaCreateDao_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockIdeaCreateDao
func (_mock *MockIdeaCreateDao) Exec(ctx context.Context, request *dao.IdeaInsertRequest) (*dao.Idea, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 *dao.Idea
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dao.IdeaInsertRequest) (*dao.Idea, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dao.IdeaInsertRequest) *dao.Idea); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dao.Idea)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dao.IdeaInsertRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIdeaCreateDao_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockIdeaCreateDao_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - request *dao.IdeaInsertRequest
func (_e *MockIdeaCreateDao_Expecter) Exec(ctx any, request any) *MockIdeaCreateDao_Exec_Call {
	return &MockIdeaCreateDao_Exec_Call{Call: _e.mock.On("Exec", ctx, request)}
}

func (_c *MockIdeaCreateDao_Exec_Call) Run(run func(ctx context.Context, request *dao.IdeaInsertRequest)) *MockIdeaCreateDao_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dao.IdeaInsertRequest
		if args[1] != nil {
			arg1 = args[1].(*dao.IdeaInsertRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIdeaCreateDao_Exec_Call) Return(idea *dao.Idea, err error) *MockIdeaCreateDao_Exec_Call {
	_c.Call.Return(idea, err)
	return _c
}

func (_c *MockIdeaCreateDao_Exec_Call) RunAndReturn(run func(ctx context.Context, request *dao.IdeaInsertRequest) (*dao.Idea, error)) *MockIdeaCreateDao_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIdeaVersionInsertDao creates a new instance of MockIdeaVersionInsertDao. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIdeaVersionInsertDao(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIdeaVersionInsertDao {
	mock := &MockIdeaVersionInsertDao{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIdeaVersionInsertDao is an autogenerated mock type for the IdeaVersionInsertDao type
type MockIdeaVersionInsertDao struct {
	mock.Mock
}

type MockIdeaVersionInsertDao_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIdeaVersionInsertDao) EXPECT() *MockIdeaVersionInsertDao_Expecter {
	return &MockIdeaVersionInsertDao_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockIdeaVersionInsertDao
func (_mock *MockIdeaVersionInsertDao) Exec(ctx context.Context, request *dao.IdeaVersionInsertRequest) (*dao.IdeaVersion, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 *dao.IdeaVersion
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dao.IdeaVersionInsertRequest) (*dao.IdeaVersion, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dao.IdeaVersionInsertRequest) *dao.IdeaVersion); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dao.IdeaVersion)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dao.IdeaVersionInsertRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIdeaVersionInsertDao_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockIdeaVersionInsertDao_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - request *dao.IdeaVersionInsertRequest
func (_e *MockIdeaVersionInsertDao_Expecter) Exec(ctx any, request any) *MockIdeaVersionInsertDao_Exec_Call {
	return &MockIdeaVersionInsertDao_Exec_Call{Call: _e.mock.On("Exec", ctx, request)}
}

func (_c *MockIdeaVersionInsertDao_Exec_Call) Run(run func(ctx context.Context, request *dao.IdeaVersionInsertRequest)) *MockIdeaVersionInsertDao_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dao.IdeaVersionInsertRequest
		if args[1] != nil {
			arg1 = args[1].(*dao.IdeaVersionInsertRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIdeaVersionInsertDao_Exec_Call) Return(ideaVersion *dao.IdeaVersion, err error) *MockIdeaVersionInsertDao_Exec_Call {
	_c.Call.Return(ideaVersion, err)
	return _c
}

func (_c *MockIdeaVersionInsertDao_Exec_Call) RunAndReturn(run func(ctx context.Context, request *dao.IdeaVersionInsertRequest) (*dao.IdeaVersion, error)) *MockIdeaVersionInsertDao_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockManuscriptInsertDao creates a new instance of MockManuscriptInsertDao. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockManuscriptInsertDao(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockManuscriptInsertDao {
	mock := &MockManuscriptInsertDao{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockManuscriptInsertDao is an autogenerated mock type for the ManuscriptInsertDao type
type MockManuscriptInsertDao struct {
	mock.Mock
}

type MockManuscriptInsertDao_Expecter struct {
	mock *mock.Mock
}

func (_m *MockManuscriptInsertDao) EXPECT() *MockManuscriptInsertDao_Expecter {
	return &MockManuscriptInsertDao_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockManuscriptInsertDao
func (_mock *MockManuscriptInsertDao) Exec(ctx context.Context, request *dao.ManuscriptInsertRequest) (*dao.Manuscript, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 *dao.Manuscript
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dao.ManuscriptInsertRequest) (*dao.Manuscript, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dao.ManuscriptInsertRequest) *dao.Manuscript); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dao.Manuscript)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dao.ManuscriptInsertRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockManuscriptInsertDao_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockManuscriptInsertDao_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - request *dao.ManuscriptInsertRequest
func (_e *MockManuscriptInsertDao_Expecter) Exec(ctx any, request any) *MockManuscriptInsertDao_Exec_Call {
	return &MockManuscriptInsertDao_Exec_Call{Call: _e.mock.On("Exec", ctx, request)}
}

func (_c *MockManuscriptInsertDao_Exec_Call) Run(run func(ctx context.Context, request *dao.ManuscriptInsertRequest)) *MockManuscriptInsertDao_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dao.ManuscriptInsertRequest
		if args[1] != nil {
			arg1 = args[1].(*dao.ManuscriptInsertRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockManuscriptInsertDao_Exec_Call) Return(manuscript *dao.Manuscript, err error) *MockManuscriptInsertDao_Exec_Call {
	_c.Call.Return(manuscript, err)
	return _c
}

func (_c *MockManuscriptInsertDao_Exec_Call) RunAndReturn(run func(ctx context.Context, request *dao.ManuscriptInsertRequest) (*dao.Manuscript, error)) *MockManuscriptInsertDao_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockProjectSelectDao creates a new instance of MockProjectSelectDao. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProjectSelectDao(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProjectSelectDao {
	mock := &MockProjectSelectDao{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockProjectSelectDao is an autogenerated mock type for the ProjectSelectDao type
type MockProjectSelectDao struct {
	mock.Mock
}

type MockProjectSelectDao_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProjectSelectDao) EXPECT() *MockProjectSelectDao_Expecter {
	return &MockProjectSelectDao_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockProjectSelectDao
func (_mock *MockProjectSelectDao) Exec(ctx context.Context, request *dao.ProjectSelectRequest) (*dao.Project, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 *dao.Project
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dao.ProjectSelectRequest) (*dao.Project, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dao.ProjectSelectRequest) *dao.Project); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dao.Project)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dao.ProjectSelectRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProjectSelectDao_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockProjectSelectDao_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - request *dao.ProjectSelectRequest
func (_e *MockProjectSelectDao_Expecter) Exec(ctx any, request any) *MockProjectSelectDao_Exec_Call {
	return &MockProjectSelectDao_Exec_Call{Call: _e.mock.On("Exec", ctx, request)}
}

func (_c *MockProjectSelectDao_Exec_Call) Run(run func(ctx context.Context, request *dao.ProjectSelectRequest)) *MockProjectSelectDao_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dao.ProjectSelectRequest
		if args[1] != nil {
			arg1 = args[1].(*dao.ProjectSelectRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProjectSelectDao_Exec_Call) Return(project *dao.Project, err error) *MockProjectSelectDao_Exec_Call {
	_c.Call.Return(project, err)
	return _c
}

func (_c *MockProjectSelectDao_Exec_Call) RunAndReturn(run func(ctx context.Context, request *dao.ProjectSelectRequest) (*dao.Project, error)) *MockProjectSelectDao_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockProjectAccessService creates a new instance of MockProjectAccessService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProjectAccessService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProjectAccessService {
	mock := &MockProjectAccessService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockProjectAccessService is an autogenerated mock type for the ProjectAccessService type
type MockProjectAccessService struct {
	mock.Mock
}

type MockProjectAccessService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProjectAccessService) EXPECT() *MockProjectAccessService_Expecter {
	return &MockProjectAccessService_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockProjectAccessService
func (_mock *MockProjectAccessService) Exec(ctx context.Context, request *core.ProjectAccessRequest) (*dao.Project, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 *dao.Project
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *core.ProjectAccessRequest) (*dao.Project, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *core.ProjectAccessRequest) *dao.Project); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dao.Project)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *core.ProjectAccessRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProjectAccessService_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockProjectAccessService_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - request *core.ProjectAccessRequest
func (_e *MockProjectAccessService_Expecter) Exec(ctx any, request any) *MockProjectAccessService_Exec_Call {
	return &MockProjectAccessService_Exec_Call{Call: _e.mock.On("Exec", ctx, request)}
}

func (_c *MockProjectAccessService_Exec_Call) Run(run func(ctx context.Context, request *core.ProjectAccessRequest)) *MockProjectAccessService_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *core.ProjectAccessRequest
		if args[1] != nil {
			arg1 = args[1].(*core.ProjectAccessRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProjectAccessService_Exec_Call) Return(project *dao.Project, err error) *MockProjectAccessService_Exec_Call {
	_c.Call.Return(project, err)
	return _c
}

func (_c *MockProjectAccessService_Exec_Call) RunAndReturn(run func(ctx context.Context, request *core.ProjectAccessRequest) (*dao.Project, error)) *MockProjectAccessService_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStepValueInsertDao creates a new instance of MockStepValueInsertDao. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStepValueInsertDao(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStepValueInsertDao {
	mock := &MockStepValueInsertDao{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStepValueInsertDao is an autogenerated mock type for the StepValueInsertDao type
type MockStepValueInsertDao struct {
	mock.Mock
}

type MockStepValueInsertDao_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStepValueInsertDao) EXPECT() *MockStepValueInsertDao_Expecter {
	return &MockStepValueInsertDao_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockStepValueInsertDao
func (_mock *MockStepValueInsertDao) Exec(ctx context.Context, request *dao.StepValueInsertRequest) (*dao.StepValue, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 *dao.StepValue
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dao.StepValueInsertRequest) (*dao.StepValue, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dao.StepValueInsertRequest) *dao.StepValue); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dao.StepValue)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dao.StepValueInsertRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStepValueInsertDao_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockStepValueInsertDao_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - request *dao.StepValueInsertRequest
func (_e *MockStepValueInsertDao_Expecter) Exec(ctx any, request any) *MockStepValueInsertDao_Exec_Call {
	return &MockStepValueInsertDao_Exec_Call{Call: _e.mock.On("Exec", ctx, request)}
}

func (_c *MockStepValueInsertDao_Exec_Call) Run(run func(ctx context.Context, request *dao.StepValueInsertRequest)) *MockStepValueInsertDao_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dao.StepValueInsertRequest
		if args[1] != nil {
			arg1 = args[1].(*dao.StepValueInsertRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStepValueInsertDao_Exec_Call) Return(stepValue *dao.StepValue, err error) *MockStepValueInsertDao_Exec_Call {
	_c.Call.Return(stepValue, err)
	return _c
}

func (_c *MockStepValueInsertDao_Exec_Call) RunAndReturn(run func(ctx context.Context, request *dao.StepValueInsertRequest) (*dao.StepValue, error)) *MockStepValueInsertDao_Exec_Call {
	_c.Call.Return(run)
	return _c
}
