services:
  postgres-json-keys:
    image: ghcr.io/a-novel/service-json-keys/database:v2.4.1
    networks:
      - narrative-engine-integration-rest-test
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
      POSTGRES_INITDB_ARGS: --auth=scram-sha-256

  service-json-keys:
    image: ghcr.io/a-novel/service-json-keys/standalone-grpc:v2.4.1
    depends_on:
      postgres-json-keys:
        condition: service_healthy
    environment:
      POSTGRES_DSN: postgres://postgres:postgres@postgres-json-keys:5432/postgres?sslmode=disable
      APP_MASTER_KEY: "${APP_MASTER_KEY}"
    networks:
      - narrative-engine-integration-rest-test

  postgres-authentication:
    image: ghcr.io/a-novel/service-authentication/database:v2.4.5
    networks:
      - narrative-engine-integration-rest-test
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
      POSTGRES_INITDB_ARGS: --auth=scram-sha-256

  service-authentication:
    image: ghcr.io/a-novel/service-authentication/standalone-rest:v2.4.5
    ports:
      - "${SERVICE_AUTHENTICATION_PORT}:8080"
    depends_on:
      postgres-authentication:
        condition: service_healthy
      service-json-keys:
        condition: service_healthy
    environment:
      POSTGRES_DSN: postgres://postgres:postgres@postgres-authentication:5432/postgres?sslmode=disable
      SERVICE_JSON_KEYS_HOST: service-json-keys
      SERVICE_JSON_KEYS_PORT: 8080
      SUPER_ADMIN_EMAIL: "${SUPER_ADMIN_EMAIL:-noreply@agorastoryverse.com}"
      SUPER_ADMIN_PASSWORD: "${SUPER_ADMIN_PASSWORD:-admin}"
    networks:
      - narrative-engine-integration-rest-test
  postgres-jobs:
    image: ghcr.io/a-novel/service-jobs/database:v0.3.0
    networks:
      - narrative-engine-integration-rest-test
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
      POSTGRES_INITDB_ARGS: --auth=scram-sha-256

  service-jobs-migrations:
    image: ghcr.io/a-novel/service-jobs/jobs/migrations:v0.2.1
    depends_on:
      postgres-jobs:
        condition: service_healthy
    environment:
      POSTGRES_DSN: postgres://postgres:postgres@postgres-jobs:5432/postgres?sslmode=disable
    networks:
      - narrative-engine-integration-rest-test

  service-jobs:
    image: ghcr.io/a-novel/service-jobs/standalone-grpc:v0.2.1
    depends_on:
      postgres-jobs:
        condition: service_healthy
      service-jobs-migrations:
        condition: service_completed_successfully
    environment:
      POSTGRES_DSN: postgres://postgres:postgres@postgres-jobs:5432/postgres?sslmode=disable
    networks:
      - narrative-engine-integration-rest-test

  postgres-narrative-engine:
    build:
      context: ..
      dockerfile: ./builds/database.Dockerfile
    networks:
      - narrative-engine-integration-rest-test
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
      POSTGRES_INITDB_ARGS: --auth=scram-sha-256

  service-narrative-engine:
    build:
      context: ..
      dockerfile: ./builds/standalone.rest.Dockerfile
    ports:
      - "${REST_PORT}:8080"
    depends_on:
      postgres-narrative-engine:
        condition: service_healthy
      service-jobs:
        condition: service_healthy
      service-json-keys:
        condition: service_healthy
    environment:
      POSTGRES_DSN: "postgres://postgres:postgres@postgres-narrative-engine:5432/${POSTGRES_DB}?sslmode=disable"
      SERVICE_JOBS_HOST: service-jobs
      SERVICE_JOBS_PORT: 8080
      SERVICE_JSON_KEYS_HOST: service-json-keys
      SERVICE_JSON_KEYS_PORT: 8080
    networks:
      - narrative-engine-integration-rest-test

networks:
  narrative-engine-integration-rest-test:
