// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package handlersmocks

import (
	"context"

	"github.com/a-novel/service-narrative-engine/internal/core"
	mock "github.com/stretchr/testify/mock"
)

// NewMockItemCreatePublicService creates a new instance of MockItemCreatePublicService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockItemCreatePublicService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockItemCreatePublicService {
	mock := &MockItemCreatePublicService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockItemCreatePublicService is an autogenerated mock type for the ItemCreatePublicService type
type MockItemCreatePublicService struct {
	mock.Mock
}

type MockItemCreatePublicService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockItemCreatePublicService) EXPECT() *MockItemCreatePublicService_Expecter {
	return &MockItemCreatePublicService_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockItemCreatePublicService
func (_mock *MockItemCreatePublicService) Exec(ctx context.Context, request *core.ItemCreateRequest) (*core.Item, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 *core.Item
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *core.ItemCreateRequest) (*core.Item, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *core.ItemCreateRequest) *core.Item); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*core.Item)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *core.ItemCreateRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockItemCreatePublicService_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockItemCreatePublicService_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - request *core.ItemCreateRequest
func (_e *MockItemCreatePublicService_Expecter) Exec(ctx any, request any) *MockItemCreatePublicService_Exec_Call {
	return &MockItemCreatePublicService_Exec_Call{Call: _e.mock.On("Exec", ctx, request)}
}

func (_c *MockItemCreatePublicService_Exec_Call) Run(run func(ctx context.Context, request *core.ItemCreateRequest)) *MockItemCreatePublicService_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *core.ItemCreateRequest
		if args[1] != nil {
			arg1 = args[1].(*core.ItemCreateRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockItemCreatePublicService_Exec_Call) Return(item *core.Item, err error) *MockItemCreatePublicService_Exec_Call {
	_c.Call.Return(item, err)
	return _c
}

func (_c *MockItemCreatePublicService_Exec_Call) RunAndReturn(run func(ctx context.Context, request *core.ItemCreateRequest) (*core.Item, error)) *MockItemCreatePublicService_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockItemDeletePublicService creates a new instance of MockItemDeletePublicService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockItemDeletePublicService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockItemDeletePublicService {
	mock := &MockItemDeletePublicService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockItemDeletePublicService is an autogenerated mock type for the ItemDeletePublicService type
type MockItemDeletePublicService struct {
	mock.Mock
}

type MockItemDeletePublicService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockItemDeletePublicService) EXPECT() *MockItemDeletePublicService_Expecter {
	return &MockItemDeletePublicService_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockItemDeletePublicService
func (_mock *MockItemDeletePublicService) Exec(ctx context.Context, request *core.ItemDeleteRequest) (*core.Item, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 *core.Item
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *core.ItemDeleteRequest) (*core.Item, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *core.ItemDeleteRequest) *core.Item); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*core.Item)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *core.ItemDeleteRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockItemDeletePublicService_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockItemDeletePublicService_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - request *core.ItemDeleteRequest
func (_e *MockItemDeletePublicService_Expecter) Exec(ctx any, request any) *MockItemDeletePublicService_Exec_Call {
	return &MockItemDeletePublicService_Exec_Call{Call: _e.mock.On("Exec", ctx, request)}
}

func (_c *MockItemDeletePublicService_Exec_Call) Run(run func(ctx context.Context, request *core.ItemDeleteRequest)) *MockItemDeletePublicService_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *core.ItemDeleteRequest
		if args[1] != nil {
			arg1 = args[1].(*core.ItemDeleteRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockItemDeletePublicService_Exec_Call) Return(item *core.Item, err error) *MockItemDeletePublicService_Exec_Call {
	_c.Call.Return(item, err)
	return _c
}

func (_c *MockItemDeletePublicService_Exec_Call) RunAndReturn(run func(ctx context.Context, request *core.ItemDeleteRequest) (*core.Item, error)) *MockItemDeletePublicService_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockItemGetPublicService creates a new instance of MockItemGetPublicService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockItemGetPublicService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockItemGetPublicService {
	mock := &MockItemGetPublicService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockItemGetPublicService is an autogenerated mock type for the ItemGetPublicService type
type MockItemGetPublicService struct {
	mock.Mock
}

type MockItemGetPublicService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockItemGetPublicService) EXPECT() *MockItemGetPublicService_Expecter {
	return &MockItemGetPublicService_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockItemGetPublicService
func (_mock *MockItemGetPublicService) Exec(ctx context.Context, request *core.ItemGetRequest) (*core.Item, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 *core.Item
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *core.ItemGetRequest) (*core.Item, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *core.ItemGetRequest) *core.Item); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*core.Item)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *core.ItemGetRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockItemGetPublicService_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockItemGetPublicService_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - request *core.ItemGetRequest
func (_e *MockItemGetPublicService_Expecter) Exec(ctx any, request any) *MockItemGetPublicService_Exec_Call {
	return &MockItemGetPublicService_Exec_Call{Call: _e.mock.On("Exec", ctx, request)}
}

func (_c *MockItemGetPublicService_Exec_Call) Run(run func(ctx context.Context, request *core.ItemGetRequest)) *MockItemGetPublicService_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *core.ItemGetRequest
		if args[1] != nil {
			arg1 = args[1].(*core.ItemGetRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockItemGetPublicService_Exec_Call) Return(item *core.Item, err error) *MockItemGetPublicService_Exec_Call {
	_c.Call.Return(item, err)
	return _c
}

func (_c *MockItemGetPublicService_Exec_Call) RunAndReturn(run func(ctx context.Context, request *core.ItemGetRequest) (*core.Item, error)) *MockItemGetPublicService_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockItemListPublicService creates a new instance of MockItemListPublicService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockItemListPublicService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockItemListPublicService {
	mock := &MockItemListPublicService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockItemListPublicService is an autogenerated mock type for the ItemListPublicService type
type MockItemListPublicService struct {
	mock.Mock
}

type MockItemListPublicService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockItemListPublicService) EXPECT() *MockItemListPublicService_Expecter {
	return &MockItemListPublicService_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockItemListPublicService
func (_mock *MockItemListPublicService) Exec(ctx context.Context, request *core.ItemListRequest) ([]*core.Item, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 []*core.Item
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *core.ItemListRequest) ([]*core.Item, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *core.ItemListRequest) []*core.Item); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*core.Item)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *core.ItemListRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockItemListPublicService_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockItemListPublicService_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - request *core.ItemListRequest
func (_e *MockItemListPublicService_Expecter) Exec(ctx any, request any) *MockItemListPublicService_Exec_Call {
	return &MockItemListPublicService_Exec_Call{Call: _e.mock.On("Exec", ctx, request)}
}

func (_c *MockItemListPublicService_Exec_Call) Run(run func(ctx context.Context, request *core.ItemListRequest)) *MockItemListPublicService_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *core.ItemListRequest
		if args[1] != nil {
			arg1 = args[1].(*core.ItemListRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockItemListPublicService_Exec_Call) Return(items []*core.Item, err error) *MockItemListPublicService_Exec_Call {
	_c.Call.Return(items, err)
	return _c
}

func (_c *MockItemListPublicService_Exec_Call) RunAndReturn(run func(ctx context.Context, request *core.ItemListRequest) ([]*core.Item, error)) *MockItemListPublicService_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockItemUpdatePublicService creates a new instance of MockItemUpdatePublicService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockItemUpdatePublicService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockItemUpdatePublicService {
	mock := &MockItemUpdatePublicService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockItemUpdatePublicService is an autogenerated mock type for the ItemUpdatePublicService type
type MockItemUpdatePublicService struct {
	mock.Mock
}

type MockItemUpdatePublicService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockItemUpdatePublicService) EXPECT() *MockItemUpdatePublicService_Expecter {
	return &MockItemUpdatePublicService_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockItemUpdatePublicService
func (_mock *MockItemUpdatePublicService) Exec(ctx context.Context, request *core.ItemUpdateRequest) (*core.Item, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 *core.Item
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *core.ItemUpdateRequest) (*core.Item, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *core.ItemUpdateRequest) *core.Item); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*core.Item)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *core.ItemUpdateRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockItemUpdatePublicService_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockItemUpdatePublicService_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - request *core.ItemUpdateRequest
func (_e *MockItemUpdatePublicService_Expecter) Exec(ctx any, request any) *MockItemUpdatePublicService_Exec_Call {
	return &MockItemUpdatePublicService_Exec_Call{Call: _e.mock.On("Exec", ctx, request)}
}

func (_c *MockItemUpdatePublicService_Exec_Call) Run(run func(ctx context.Context, request *core.ItemUpdateRequest)) *MockItemUpdatePublicService_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *core.ItemUpdateRequest
		if args[1] != nil {
			arg1 = args[1].(*core.ItemUpdateRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockItemUpdatePublicService_Exec_Call) Return(item *core.Item, err error) *MockItemUpdatePublicService_Exec_Call {
	_c.Call.Return(item, err)
	return _c
}

func (_c *MockItemUpdatePublicService_Exec_Call) RunAndReturn(run func(ctx context.Context, request *core.ItemUpdateRequest) (*core.Item, error)) *MockItemUpdatePublicService_Exec_Call {
	_c.Call.Return(run)
	return _c
}
