// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package handlersmocks

import (
	"context"

	"github.com/a-novel/service-narrative-engine/internal/core"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRestGenerationGetService creates a new instance of MockRestGenerationGetService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRestGenerationGetService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRestGenerationGetService {
	mock := &MockRestGenerationGetService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRestGenerationGetService is an autogenerated mock type for the RestGenerationGetService type
type MockRestGenerationGetService struct {
	mock.Mock
}

type MockRestGenerationGetService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRestGenerationGetService) EXPECT() *MockRestGenerationGetService_Expecter {
	return &MockRestGenerationGetService_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockRestGenerationGetService
func (_mock *MockRestGenerationGetService) Exec(ctx context.Context, request *core.GenerationGetRequest) (*core.Generation, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 *core.Generation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *core.GenerationGetRequest) (*core.Generation, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *core.GenerationGetRequest) *core.Generation); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*core.Generation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *core.GenerationGetRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRestGenerationGetService_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockRestGenerationGetService_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - request *core.GenerationGetRequest
func (_e *MockRestGenerationGetService_Expecter) Exec(ctx any, request any) *MockRestGenerationGetService_Exec_Call {
	return &MockRestGenerationGetService_Exec_Call{Call: _e.mock.On("Exec", ctx, request)}
}

func (_c *MockRestGenerationGetService_Exec_Call) Run(run func(ctx context.Context, request *core.GenerationGetRequest)) *MockRestGenerationGetService_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *core.GenerationGetRequest
		if args[1] != nil {
			arg1 = args[1].(*core.GenerationGetRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRestGenerationGetService_Exec_Call) Return(generation *core.Generation, err error) *MockRestGenerationGetService_Exec_Call {
	_c.Call.Return(generation, err)
	return _c
}

func (_c *MockRestGenerationGetService_Exec_Call) RunAndReturn(run func(ctx context.Context, request *core.GenerationGetRequest) (*core.Generation, error)) *MockRestGenerationGetService_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRestGenerationSubmitService creates a new instance of MockRestGenerationSubmitService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRestGenerationSubmitService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRestGenerationSubmitService {
	mock := &MockRestGenerationSubmitService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRestGenerationSubmitService is an autogenerated mock type for the RestGenerationSubmitService type
type MockRestGenerationSubmitService struct {
	mock.Mock
}

type MockRestGenerationSubmitService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRestGenerationSubmitService) EXPECT() *MockRestGenerationSubmitService_Expecter {
	return &MockRestGenerationSubmitService_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockRestGenerationSubmitService
func (_mock *MockRestGenerationSubmitService) Exec(ctx context.Context, request *core.GenerationSubmitRequest) (*core.GenerationSubmitResult, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 *core.GenerationSubmitResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *core.GenerationSubmitRequest) (*core.GenerationSubmitResult, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *core.GenerationSubmitRequest) *core.GenerationSubmitResult); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*core.GenerationSubmitResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *core.GenerationSubmitRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRestGenerationSubmitService_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockRestGenerationSubmitService_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - request *core.GenerationSubmitRequest
func (_e *MockRestGenerationSubmitService_Expecter) Exec(ctx any, request any) *MockRestGenerationSubmitService_Exec_Call {
	return &MockRestGenerationSubmitService_Exec_Call{Call: _e.mock.On("Exec", ctx, request)}
}

func (_c *MockRestGenerationSubmitService_Exec_Call) Run(run func(ctx context.Context, request *core.GenerationSubmitRequest)) *MockRestGenerationSubmitService_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *core.GenerationSubmitRequest
		if args[1] != nil {
			arg1 = args[1].(*core.GenerationSubmitRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRestGenerationSubmitService_Exec_Call) Return(generationSubmitResult *core.GenerationSubmitResult, err error) *MockRestGenerationSubmitService_Exec_Call {
	_c.Call.Return(generationSubmitResult, err)
	return _c
}

func (_c *MockRestGenerationSubmitService_Exec_Call) RunAndReturn(run func(ctx context.Context, request *core.GenerationSubmitRequest) (*core.GenerationSubmitResult, error)) *MockRestGenerationSubmitService_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRestIdeaHistoryService creates a new instance of MockRestIdeaHistoryService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRestIdeaHistoryService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRestIdeaHistoryService {
	mock := &MockRestIdeaHistoryService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRestIdeaHistoryService is an autogenerated mock type for the RestIdeaHistoryService type
type MockRestIdeaHistoryService struct {
	mock.Mock
}

type MockRestIdeaHistoryService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRestIdeaHistoryService) EXPECT() *MockRestIdeaHistoryService_Expecter {
	return &MockRestIdeaHistoryService_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockRestIdeaHistoryService
func (_mock *MockRestIdeaHistoryService) Exec(ctx context.Context, request *core.IdeaHistoryRequest) ([]*core.Idea, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 []*core.Idea
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *core.IdeaHistoryRequest) ([]*core.Idea, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *core.IdeaHistoryRequest) []*core.Idea); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*core.Idea)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *core.IdeaHistoryRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRestIdeaHistoryService_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockRestIdeaHistoryService_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - request *core.IdeaHistoryRequest
func (_e *MockRestIdeaHistoryService_Expecter) Exec(ctx any, request any) *MockRestIdeaHistoryService_Exec_Call {
	return &MockRestIdeaHistoryService_Exec_Call{Call: _e.mock.On("Exec", ctx, request)}
}

func (_c *MockRestIdeaHistoryService_Exec_Call) Run(run func(ctx context.Context, request *core.IdeaHistoryRequest)) *MockRestIdeaHistoryService_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *core.IdeaHistoryRequest
		if args[1] != nil {
			arg1 = args[1].(*core.IdeaHistoryRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRestIdeaHistoryService_Exec_Call) Return(ideas []*core.Idea, err error) *MockRestIdeaHistoryService_Exec_Call {
	_c.Call.Return(ideas, err)
	return _c
}

func (_c *MockRestIdeaHistoryService_Exec_Call) RunAndReturn(run func(ctx context.Context, request *core.IdeaHistoryRequest) ([]*core.Idea, error)) *MockRestIdeaHistoryService_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRestIdeaVersionCreateService creates a new instance of MockRestIdeaVersionCreateService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRestIdeaVersionCreateService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRestIdeaVersionCreateService {
	mock := &MockRestIdeaVersionCreateService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRestIdeaVersionCreateService is an autogenerated mock type for the RestIdeaVersionCreateService type
type MockRestIdeaVersionCreateService struct {
	mock.Mock
}

type MockRestIdeaVersionCreateService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRestIdeaVersionCreateService) EXPECT() *MockRestIdeaVersionCreateService_Expecter {
	return &MockRestIdeaVersionCreateService_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockRestIdeaVersionCreateService
func (_mock *MockRestIdeaVersionCreateService) Exec(ctx context.Context, request *core.IdeaVersionCreateRequest) (*core.Idea, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 *core.Idea
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *core.IdeaVersionCreateRequest) (*core.Idea, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *core.IdeaVersionCreateRequest) *core.Idea); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*core.Idea)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *core.IdeaVersionCreateRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRestIdeaVersionCreateService_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockRestIdeaVersionCreateService_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - request *core.IdeaVersionCreateRequest
func (_e *MockRestIdeaVersionCreateService_Expecter) Exec(ctx any, request any) *MockRestIdeaVersionCreateService_Exec_Call {
	return &MockRestIdeaVersionCreateService_Exec_Call{Call: _e.mock.On("Exec", ctx, request)}
}

func (_c *MockRestIdeaVersionCreateService_Exec_Call) Run(run func(ctx context.Context, request *core.IdeaVersionCreateRequest)) *MockRestIdeaVersionCreateService_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *core.IdeaVersionCreateRequest
		if args[1] != nil {
			arg1 = args[1].(*core.IdeaVersionCreateRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRestIdeaVersionCreateService_Exec_Call) Return(idea *core.Idea, err error) *MockRestIdeaVersionCreateService_Exec_Call {
	_c.Call.Return(idea, err)
	return _c
}

func (_c *MockRestIdeaVersionCreateService_Exec_Call) RunAndReturn(run func(ctx context.Context, request *core.IdeaVersionCreateRequest) (*core.Idea, error)) *MockRestIdeaVersionCreateService_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRestManuscriptCreateService creates a new instance of MockRestManuscriptCreateService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRestManuscriptCreateService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRestManuscriptCreateService {
	mock := &MockRestManuscriptCreateService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRestManuscriptCreateService is an autogenerated mock type for the RestManuscriptCreateService type
type MockRestManuscriptCreateService struct {
	mock.Mock
}

type MockRestManuscriptCreateService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRestManuscriptCreateService) EXPECT() *MockRestManuscriptCreateService_Expecter {
	return &MockRestManuscriptCreateService_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockRestManuscriptCreateService
func (_mock *MockRestManuscriptCreateService) Exec(ctx context.Context, request *core.ManuscriptCreateRequest) (*core.Manuscript, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 *core.Manuscript
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *core.ManuscriptCreateRequest) (*core.Manuscript, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *core.ManuscriptCreateRequest) *core.Manuscript); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*core.Manuscript)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *core.ManuscriptCreateRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRestManuscriptCreateService_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockRestManuscriptCreateService_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - request *core.ManuscriptCreateRequest
func (_e *MockRestManuscriptCreateService_Expecter) Exec(ctx any, request any) *MockRestManuscriptCreateService_Exec_Call {
	return &MockRestManuscriptCreateService_Exec_Call{Call: _e.mock.On("Exec", ctx, request)}
}

func (_c *MockRestManuscriptCreateService_Exec_Call) Run(run func(ctx context.Context, request *core.ManuscriptCreateRequest)) *MockRestManuscriptCreateService_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *core.ManuscriptCreateRequest
		if args[1] != nil {
			arg1 = args[1].(*core.ManuscriptCreateRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRestManuscriptCreateService_Exec_Call) Return(manuscript *core.Manuscript, err error) *MockRestManuscriptCreateService_Exec_Call {
	_c.Call.Return(manuscript, err)
	return _c
}

func (_c *MockRestManuscriptCreateService_Exec_Call) RunAndReturn(run func(ctx context.Context, request *core.ManuscriptCreateRequest) (*core.Manuscript, error)) *MockRestManuscriptCreateService_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRestManuscriptHistoryService creates a new instance of MockRestManuscriptHistoryService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRestManuscriptHistoryService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRestManuscriptHistoryService {
	mock := &MockRestManuscriptHistoryService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRestManuscriptHistoryService is an autogenerated mock type for the RestManuscriptHistoryService type
type MockRestManuscriptHistoryService struct {
	mock.Mock
}

type MockRestManuscriptHistoryService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRestManuscriptHistoryService) EXPECT() *MockRestManuscriptHistoryService_Expecter {
	return &MockRestManuscriptHistoryService_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockRestManuscriptHistoryService
func (_mock *MockRestManuscriptHistoryService) Exec(ctx context.Context, request *core.ManuscriptHistoryRequest) ([]*core.Manuscript, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 []*core.Manuscript
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *core.ManuscriptHistoryRequest) ([]*core.Manuscript, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *core.ManuscriptHistoryRequest) []*core.Manuscript); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*core.Manuscript)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *core.ManuscriptHistoryRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRestManuscriptHistoryService_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockRestManuscriptHistoryService_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - request *core.ManuscriptHistoryRequest
func (_e *MockRestManuscriptHistoryService_Expecter) Exec(ctx any, request any) *MockRestManuscriptHistoryService_Exec_Call {
	return &MockRestManuscriptHistoryService_Exec_Call{Call: _e.mock.On("Exec", ctx, request)}
}

func (_c *MockRestManuscriptHistoryService_Exec_Call) Run(run func(ctx context.Context, request *core.ManuscriptHistoryRequest)) *MockRestManuscriptHistoryService_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *core.ManuscriptHistoryRequest
		if args[1] != nil {
			arg1 = args[1].(*core.ManuscriptHistoryRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRestManuscriptHistoryService_Exec_Call) Return(manuscripts []*core.Manuscript, err error) *MockRestManuscriptHistoryService_Exec_Call {
	_c.Call.Return(manuscripts, err)
	return _c
}

func (_c *MockRestManuscriptHistoryService_Exec_Call) RunAndReturn(run func(ctx context.Context, request *core.ManuscriptHistoryRequest) ([]*core.Manuscript, error)) *MockRestManuscriptHistoryService_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRestProjectCreateService creates a new instance of MockRestProjectCreateService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRestProjectCreateService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRestProjectCreateService {
	mock := &MockRestProjectCreateService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRestProjectCreateService is an autogenerated mock type for the RestProjectCreateService type
type MockRestProjectCreateService struct {
	mock.Mock
}

type MockRestProjectCreateService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRestProjectCreateService) EXPECT() *MockRestProjectCreateService_Expecter {
	return &MockRestProjectCreateService_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockRestProjectCreateService
func (_mock *MockRestProjectCreateService) Exec(ctx context.Context, request *core.IdeaCreateRequest) (*core.Idea, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 *core.Idea
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *core.IdeaCreateRequest) (*core.Idea, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *core.IdeaCreateRequest) *core.Idea); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*core.Idea)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *core.IdeaCreateRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRestProjectCreateService_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockRestProjectCreateService_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - request *core.IdeaCreateRequest
func (_e *MockRestProjectCreateService_Expecter) Exec(ctx any, request any) *MockRestProjectCreateService_Exec_Call {
	return &MockRestProjectCreateService_Exec_Call{Call: _e.mock.On("Exec", ctx, request)}
}

func (_c *MockRestProjectCreateService_Exec_Call) Run(run func(ctx context.Context, request *core.IdeaCreateRequest)) *MockRestProjectCreateService_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *core.IdeaCreateRequest
		if args[1] != nil {
			arg1 = args[1].(*core.IdeaCreateRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRestProjectCreateService_Exec_Call) Return(idea *core.Idea, err error) *MockRestProjectCreateService_Exec_Call {
	_c.Call.Return(idea, err)
	return _c
}

func (_c *MockRestProjectCreateService_Exec_Call) RunAndReturn(run func(ctx context.Context, request *core.IdeaCreateRequest) (*core.Idea, error)) *MockRestProjectCreateService_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRestProjectGetService creates a new instance of MockRestProjectGetService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRestProjectGetService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRestProjectGetService {
	mock := &MockRestProjectGetService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRestProjectGetService is an autogenerated mock type for the RestProjectGetService type
type MockRestProjectGetService struct {
	mock.Mock
}

type MockRestProjectGetService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRestProjectGetService) EXPECT() *MockRestProjectGetService_Expecter {
	return &MockRestProjectGetService_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockRestProjectGetService
func (_mock *MockRestProjectGetService) Exec(ctx context.Context, request *core.ProjectGetRequest) (*core.ProjectSnapshot, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 *core.ProjectSnapshot
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *core.ProjectGetRequest) (*core.ProjectSnapshot, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *core.ProjectGetRequest) *core.ProjectSnapshot); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*core.ProjectSnapshot)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *core.ProjectGetRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRestProjectGetService_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockRestProjectGetService_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - request *core.ProjectGetRequest
func (_e *MockRestProjectGetService_Expecter) Exec(ctx any, request any) *MockRestProjectGetService_Exec_Call {
	return &MockRestProjectGetService_Exec_Call{Call: _e.mock.On("Exec", ctx, request)}
}

func (_c *MockRestProjectGetService_Exec_Call) Run(run func(ctx context.Context, request *core.ProjectGetRequest)) *MockRestProjectGetService_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *core.ProjectGetRequest
		if args[1] != nil {
			arg1 = args[1].(*core.ProjectGetRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRestProjectGetService_Exec_Call) Return(projectSnapshot *core.ProjectSnapshot, err error) *MockRestProjectGetService_Exec_Call {
	_c.Call.Return(projectSnapshot, err)
	return _c
}

func (_c *MockRestProjectGetService_Exec_Call) RunAndReturn(run func(ctx context.Context, request *core.ProjectGetRequest) (*core.ProjectSnapshot, error)) *MockRestProjectGetService_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRestStepValueCreateService creates a new instance of MockRestStepValueCreateService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRestStepValueCreateService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRestStepValueCreateService {
	mock := &MockRestStepValueCreateService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRestStepValueCreateService is an autogenerated mock type for the RestStepValueCreateService type
type MockRestStepValueCreateService struct {
	mock.Mock
}

type MockRestStepValueCreateService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRestStepValueCreateService) EXPECT() *MockRestStepValueCreateService_Expecter {
	return &MockRestStepValueCreateService_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockRestStepValueCreateService
func (_mock *MockRestStepValueCreateService) Exec(ctx context.Context, request *core.StepValueCreateRequest) (*core.StepValue, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 *core.StepValue
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *core.StepValueCreateRequest) (*core.StepValue, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *core.StepValueCreateRequest) *core.StepValue); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*core.StepValue)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *core.StepValueCreateRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRestStepValueCreateService_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockRestStepValueCreateService_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - request *core.StepValueCreateRequest
func (_e *MockRestStepValueCreateService_Expecter) Exec(ctx any, request any) *MockRestStepValueCreateService_Exec_Call {
	return &MockRestStepValueCreateService_Exec_Call{Call: _e.mock.On("Exec", ctx, request)}
}

func (_c *MockRestStepValueCreateService_Exec_Call) Run(run func(ctx context.Context, request *core.StepValueCreateRequest)) *MockRestStepValueCreateService_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *core.StepValueCreateRequest
		if args[1] != nil {
			arg1 = args[1].(*core.StepValueCreateRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRestStepValueCreateService_Exec_Call) Return(stepValue *core.StepValue, err error) *MockRestStepValueCreateService_Exec_Call {
	_c.Call.Return(stepValue, err)
	return _c
}

func (_c *MockRestStepValueCreateService_Exec_Call) RunAndReturn(run func(ctx context.Context, request *core.StepValueCreateRequest) (*core.StepValue, error)) *MockRestStepValueCreateService_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRestStepValueHistoryService creates a new instance of MockRestStepValueHistoryService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRestStepValueHistoryService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRestStepValueHistoryService {
	mock := &MockRestStepValueHistoryService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRestStepValueHistoryService is an autogenerated mock type for the RestStepValueHistoryService type
type MockRestStepValueHistoryService struct {
	mock.Mock
}

type MockRestStepValueHistoryService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRestStepValueHistoryService) EXPECT() *MockRestStepValueHistoryService_Expecter {
	return &MockRestStepValueHistoryService_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockRestStepValueHistoryService
func (_mock *MockRestStepValueHistoryService) Exec(ctx context.Context, request *core.StepValueHistoryRequest) ([]*core.StepValue, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 []*core.StepValue
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *core.StepValueHistoryRequest) ([]*core.StepValue, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *core.StepValueHistoryRequest) []*core.StepValue); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*core.StepValue)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *core.StepValueHistoryRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRestStepValueHistoryService_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockRestStepValueHistoryService_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - request *core.StepValueHistoryRequest
func (_e *MockRestStepValueHistoryService_Expecter) Exec(ctx any, request any) *MockRestStepValueHistoryService_Exec_Call {
	return &MockRestStepValueHistoryService_Exec_Call{Call: _e.mock.On("Exec", ctx, request)}
}

func (_c *MockRestStepValueHistoryService_Exec_Call) Run(run func(ctx context.Context, request *core.StepValueHistoryRequest)) *MockRestStepValueHistoryService_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *core.StepValueHistoryRequest
		if args[1] != nil {
			arg1 = args[1].(*core.StepValueHistoryRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRestStepValueHistoryService_Exec_Call) Return(stepValues []*core.StepValue, err error) *MockRestStepValueHistoryService_Exec_Call {
	_c.Call.Return(stepValues, err)
	return _c
}

func (_c *MockRestStepValueHistoryService_Exec_Call) RunAndReturn(run func(ctx context.Context, request *core.StepValueHistoryRequest) ([]*core.StepValue, error)) *MockRestStepValueHistoryService_Exec_Call {
	_c.Call.Return(run)
	return _c
}
